import sqlite3
import sys
import tempfile
import unittest
from pathlib import Path


BACKEND_DIR = Path(__file__).resolve().parents[1] / "backend"
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

from db.profiles import DatabaseProfile  # noqa: E402
from db.schema import RUNTIME_TABLES, initialize_schema, schema_statements  # noqa: E402


def profile(db_type: str, path: str = ":memory:") -> DatabaseProfile:
    if db_type == "sqlite":
        return DatabaseProfile("sqlite_test", "sqlite", {"type": "sqlite", "path": path, "database": path})
    return DatabaseProfile(
        f"{db_type}_test",
        db_type,
        {
            "type": db_type,
            "host": "127.0.0.1",
            "port": 5432,
            "database": "code_audit_test",
            "username": "change_me",
            "password": "change_me",
            "schema": "public",
        },
    )


class CaptureRunner:
    def __init__(self):
        self.statements = []

    def execute(self, statement):
        self.statements.append(statement)


class SchemaTests(unittest.TestCase):
    def test_runtime_table_manifest_contains_five_tables(self):
        self.assertEqual(
            set(RUNTIME_TABLES),
            {"projects", "audit_tasks", "task_reports", "audit_results", "fine_report_items"},
        )

    def test_sqlite_initialization_creates_tables_and_is_idempotent(self):
        with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
            db_path = str(Path(tmp) / "schema.db")
            sqlite = profile("sqlite", db_path)
            initialize_schema(sqlite)
            initialize_schema(sqlite)
            with sqlite3.connect(db_path) as connection:
                rows = connection.execute(
                    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'"
                ).fetchall()
        self.assertEqual({row[0] for row in rows}, set(RUNTIME_TABLES))

    def test_pg_schema_generates_expected_statements(self):
        statements = schema_statements(profile("postgresql"))
        text = "\n".join(statements)
        for table in RUNTIME_TABLES:
            self.assertIn(f"CREATE TABLE IF NOT EXISTS {table}", text)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", text)

    def test_dws_schema_generates_expected_statements(self):
        statements = schema_statements(profile("dws"))
        text = "\n".join(statements)
        for table in RUNTIME_TABLES:
            self.assertIn(f"CREATE TABLE IF NOT EXISTS {table}", text)
        self.assertNotIn("jsonb", text.lower())
        self.assertNotIn("ON CONFLICT", text)

    def test_pg_and_dws_mock_execution(self):
        for db_type in ("postgresql", "dws"):
            runner = CaptureRunner()
            initialize_schema(profile(db_type), runner=runner)
            self.assertEqual(len(runner.statements), 5)
            self.assertTrue(all(statement.startswith("CREATE TABLE IF NOT EXISTS") for statement in runner.statements))


if __name__ == "__main__":
    unittest.main()
