# -*- coding: utf-8 -*-
"""Compatibility facade for audit path, lineage, and file-analysis helpers."""

from .file_io_analysis import (
    clear_folder,
    detect_file_format,
    extract_pronames,
    extract_tables,
    extract_values,
    find_dot_strings,
    find_hardcoded_dates,
    find_unique_elements_with_count,
    get_result,
    has_send_proname,
    is_chinese,
    is_send_proname,
    load_txt_to_df,
    load_txt_to_df2,
    load_xls_to_df,
    read_data_from_file,
    read_excel_file,
)
from .lineage_loader import (
    build_dependency_table_lookup,
    build_job_outfile_lookup,
    build_lineage_row_lookup,
    build_program_lookup,
    build_wide_table_lineage_summary,
    get_dependency_items,
    get_program_lookup_result,
    get_yilai_table_from_lookup,
    merge_job_program,
)
from .path_export import (
    build_export_download_link,
    build_export_download_url,
    get_export_base,
    get_export_http_root,
    get_filename,
    match_any,
    match_path,
    normalize_path,
    safe_remove_prefix,
    tail_path,
)

__all__ = [
    "build_dependency_table_lookup",
    "build_export_download_link",
    "build_export_download_url",
    "build_job_outfile_lookup",
    "build_lineage_row_lookup",
    "build_program_lookup",
    "build_wide_table_lineage_summary",
    "clear_folder",
    "detect_file_format",
    "extract_pronames",
    "extract_tables",
    "extract_values",
    "find_dot_strings",
    "find_hardcoded_dates",
    "find_unique_elements_with_count",
    "get_dependency_items",
    "get_export_base",
    "get_export_http_root",
    "get_filename",
    "get_program_lookup_result",
    "get_result",
    "get_yilai_table_from_lookup",
    "has_send_proname",
    "is_chinese",
    "is_send_proname",
    "load_txt_to_df",
    "load_txt_to_df2",
    "load_xls_to_df",
    "match_any",
    "match_path",
    "merge_job_program",
    "normalize_path",
    "read_data_from_file",
    "read_excel_file",
    "safe_remove_prefix",
    "tail_path",
]
