"""Static, typed metadata for business audit rules.

This registry describes existing checks only. It neither configures policies nor
executes a checker; policy values remain in audit_rules.yaml and behavior stays
in the workflow implementation.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from types import MappingProxyType
from typing import Literal


Workflow = Literal["hcyt", "nups", "fine-report"]
Category = Literal[
    "sql", "ddl", "python", "script", "schedule", "dependency",
    "metadata", "asset_registry", "config", "menu", "permission", "report",
]
Severity = Literal["err", "warn"]


@dataclass(frozen=True, slots=True)
class RuleImplementation:
    module: str
    function: str


@dataclass(frozen=True, slots=True)
class RuleDefinition:
    id: str
    workflow: Workflow
    category: Category
    title: str
    default_severity: Severity
    description: str
    rationale: str
    trigger_condition: str
    artifact: str
    config_keys: tuple[str, ...]
    implementation: tuple[RuleImplementation, ...]


def _rule(
    rule_id: str,
    workflow: Workflow,
    category: Category,
    title: str,
    severity: Severity,
    description: str,
    rationale: str,
    trigger: str,
    artifact: str,
    module: str,
    function: str,
    config: tuple[str, ...] = (),
    additional_implementations: tuple[RuleImplementation, ...] = (),
) -> RuleDefinition:
    return RuleDefinition(
        id=rule_id,
        workflow=workflow,
        category=category,
        title=title,
        default_severity=severity,
        description=description,
        rationale=rationale,
        trigger_condition=trigger,
        artifact=artifact,
        config_keys=config,
        implementation=(RuleImplementation(module, function), *additional_implementations),
    )


_HCYT_PY = "app.modules.audit.workflows.hcyt.checks.python_rule"
_HCYT_SQL = "app.modules.audit.workflows.hcyt.checks.sql_rule"
_HCYT_DDL = "app.modules.audit.workflows.hcyt.checks.ddl_rule"
_HCYT_SCHEDULE = "app.modules.audit.workflows.hcyt.checks.schedule_rule"
_HCYT_SENSITIVE_SQL = "app.modules.audit.workflows.hcyt.checks.sensitive_sql"
_NUPS = "app.modules.audit.workflows.nups.checks"
_FINE = "app.modules.audit.workflows.fine_report.checks"
_SHARED_DWS = "app.modules.audit.shared.dws_sql_review"


def _hcyt(
    rule_id: str, category: Category, title: str, severity: Severity,
    description: str, rationale: str, trigger: str, artifact: str,
    module: str, function: str, config: tuple[str, ...] = (),
    additional_implementations: tuple[RuleImplementation, ...] = (),
) -> RuleDefinition:
    return _rule(rule_id, "hcyt", category, title, severity, description, rationale,
                 trigger, artifact, module, function, config, additional_implementations)


def _nups(
    rule_id: str, category: Category, title: str, severity: Severity,
    description: str, rationale: str, trigger: str, artifact: str,
    module: str, function: str, config: tuple[str, ...] = (),
) -> RuleDefinition:
    return _rule(rule_id, "nups", category, title, severity, description, rationale,
                 trigger, artifact, module, function, config)


def _fine(
    rule_id: str, category: Category, title: str, severity: Severity,
    description: str, rationale: str, trigger: str, artifact: str,
    function: str, config: tuple[str, ...] = (),
) -> RuleDefinition:
    return _rule(rule_id, "fine-report", category, title, severity, description, rationale,
                 trigger, artifact, _FINE, function, config)


RULES: tuple[RuleDefinition, ...] = (
    # HCYT: configuration, DDL, file, SQL and program rules.
    _hcyt("hcyt.ddl.temp_table_name", "ddl", "临时表名必须使用 TMP_ 前缀", "err",
          "检查临时表或 TMP schema 下的表名是否以配置的临时表前缀开头。",
          "临时对象未使用约定前缀，可能被误认为持久业务表或无法按临时表约定管理。",
          "当可解析的 CREATE TABLE 或 ALTER TABLE 对象属于临时表，且表名不匹配任一配置前缀时触发。",
          "DWS DDL 中的表对象", _HCYT_DDL, "check_table_name_rule",
          ("dws.naming.temporary_table_prefixes",)),
    _hcyt("hcyt.ddl.table_name", "ddl", "分层表名必须符合 schema 前缀", "err",
          "检查 DWF、DWM、DWA、DWP、DWD schema 下的表名是否以对应配置前缀开头。",
          "分层表名前缀不匹配会使对象难以按数据层识别，并可能造成依赖方误用。",
          "当 CREATE TABLE、ALTER TABLE 或加工程序结果表属于已配置 schema，且表名未匹配该 schema 的任何前缀时触发。",
          "DWS DDL 表对象或加工程序结果表", _HCYT_DDL, "check_table_name_rule",
          ("dws.naming.schema_prefixes",)),
    _hcyt("hcyt.ddl.column_comment", "ddl", "指定分层表的字段必须有注释", "err",
          "检查必需 schema 中的建表字段是否具有行内 COMMENT 或对应 COMMENT ON COLUMN。",
          "没有字段说明时，下游使用者无法从表结构确认字段含义，容易误用或重复解释字段。",
          "当字段所属 schema 在 comment_required_schemas 中，且两种注释位置均为空时触发。",
          "DWS CREATE TABLE / ALTER TABLE 的字段定义", _HCYT_DDL, "check_column_comment_rule",
          ("dws.naming.comment_required_schemas",)),
    _hcyt("hcyt.ddl.table_root", "ddl", "指定分层表名词根必须登记", "err",
          "检查适用范围内的表名是否只使用已登记的资产词根。",
          "未登记的词根无法按现有资产词汇检索和解释，可能造成表名语义不一致。",
          "仅当词根元数据可读取、表名可解析且 schema 在 root_check_required_schemas 中时，存在未登记词段即触发。",
          "DWS CREATE TABLE 的表名", _HCYT_DDL, "check_table_root_rule",
          ("dws.naming.root_check_required_schemas", "dws.naming.schema_prefixes",
           "dws.naming.temporary_table_prefixes")),
    _hcyt("hcyt.ddl.column_root", "ddl", "指定分层字段名词根必须登记", "err",
          "检查适用范围内的字段名是否只使用已登记的资产词根。",
          "未登记的字段词根难以按统一词汇检索和解释，可能使相同业务含义出现不同命名。",
          "仅当词根元数据可读取、字段定义可解析且表 schema 在 root_check_required_schemas 中时，存在未登记词段即触发。",
          "DWS CREATE TABLE / ALTER TABLE 的字段名", _HCYT_DDL, "check_column_root_rule",
          ("dws.naming.root_check_required_schemas",)),
    _hcyt("hcyt.dwf.empty_code_mapping", "metadata", "DWF 码值映射字段不得为空", "err",
          "检查 DWF 文件是否包含空的 SRC_TBL_ENG_NM 或 SRC_CD_FLD_ENG_NM 赋值。",
          "缺少来源表或来源码值字段会使码值映射关系无法确定。",
          "读取 DWF 文件后，大小写不敏感地匹配任一指定空赋值文本时触发。",
          "DWF 加工文件", _HCYT_PY, "rule_dwf"),
    _hcyt("hcyt.dwo.legacy_version", "python", "湖仓联通 DWO 不得使用 1.0 模板", "err",
          "检查 DWO 文件是否同时包含旧模板版本标记和湖仓联通加工算法描述。",
          "旧版模板可能不符合当前湖仓联通作业所需的字段或处理约定。",
          "当文件同时包含“版 本 号: v 1.0”和“功能描述: 湖仓联通加工算法”文本时触发。",
          "DWO 加工文件", _HCYT_PY, "rule_dwo"),
    _hcyt("hcyt.recv.custom_export", "config", "自定义卸数配置须显式复核", "err",
          "检查自定义卸数配置是否符合系统内置的常见生产配置形式。",
          "自定义卸数配置可能使用非生产 schema；若源环境信息错误，作业会读取错误环境的数据。",
          "当路径不含 003.DLK_DLO.、010.DWS_DWF. 或 LOCAL_，并且内容不含“\"sql\" : \"\"”时触发；匹配采用大小写不敏感方式。",
          "recv JSON 配置文件", _HCYT_PY, "rule_recv_json"),
    _hcyt("hcyt.sbin.tab_character", "script", "后置 Python 脚本不得包含 TAB", "err",
          "检查扩展名为 .py 的后置脚本内容是否包含制表符字符。",
          "TAB 与空格混用可能造成 Python 缩进错误，也会使脚本显示和编辑结果不一致。",
          "当被分类为后置脚本的 .py 文件中出现任意 TAB 字符时触发；字符串和注释中的 TAB 也会命中。",
          "后置 Python 脚本", _HCYT_PY, "rule_sbin"),
    _hcyt("hcyt.sbin.dos_format", "script", "后置脚本必须使用 UNIX 换行格式", "err",
          "检查后置脚本是否使用 DOS 换行格式。",
          "不同平台的换行格式可能导致部署脚本或解释器对文件内容的处理不一致。",
          "当后置脚本换行格式被识别为 DOS 时触发。",
          "后置脚本文件", _HCYT_PY, "rule_sbin"),

    # HCYT program source rules. Text-pattern findings are intentionally described as heuristics.
    _hcyt("hcyt.program.create_view", "python", "加工程序中的视图定义须重点复核", "err",
          "检查加工程序中的 SQL 是否包含视图定义。",
          "视图定义会新增或改变共享数据库对象，未经核对可能影响其他作业的引用结果。",
          "当程序 SQL 中出现 CREATE VIEW 定义时触发。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.create_function", "python", "加工程序中的函数定义须重点复核", "err",
          "检查加工程序中的 SQL 是否包含函数定义。",
          "函数定义会新增共享数据库对象，调用方可能在未协调的情况下依赖其行为。",
          "当程序 SQL 中出现 CREATE FUNCTION 定义时触发。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.recursive_query", "python", "加工程序不得包含递归查询标记", "err",
          "检查加工程序中是否出现递归查询相关写法。",
          "递归查询可能逐轮扩大处理范围，输入边界不明确时可能导致长时间运行或资源消耗。",
          "读取程序文本后，只要大写化文本中出现 RECURSIVE 即触发；注释和字符串也可能命中。",
          "DWS 加工 Python 文件及其中的 SQL 文本", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.for_loop", "python", "加工程序不得包含 FOR I IN 文本模式", "err",
          "检查加工程序中是否出现 FOR 循环相关写法。",
          "被识别为批内循环的逻辑可能重复执行查询或写入并延长作业时间。",
          "读取程序文本后，出现连续文本 FOR I IN 即触发；该匹配不判断其是否为实际 Python 循环。",
          "DWS 加工 Python 文件", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.character_varying_length", "python", "加工程序不得声明定长 CHARACTER VARYING", "err",
          "检查加工程序是否使用 CHARACTER VARYING 定长字段类型。",
          "固定字符串长度可能无法容纳后续出现的较长值，导致写入截断或失败。",
          "读取程序文本并转为大写后，出现 CHARACTER VARYING( 即触发；不解析列定义。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.varchar2_length", "python", "加工程序不得声明定长 VARCHAR2", "err",
          "检查加工程序是否使用 VARCHAR2 定长字段类型。",
          "固定字符串长度可能无法容纳后续出现的较长值，导致写入截断或失败。",
          "读取程序文本并转为大写后，出现 VARCHAR2( 即触发；不解析列定义。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.nested_nvl", "python", "加工程序不得嵌套调用 NVL", "err",
          "检查加工程序是否存在嵌套的 NVL 空值处理。",
          "多层空值回退会使最终取值路径难以核对，并可能隐藏字段为空时的错误默认值。",
          "读取程序文本并转为大写后，出现 NVL(NVL( 即触发；不解析函数调用树。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.nested_coalesce", "python", "加工程序不得嵌套调用 COALESCE", "err",
          "检查加工程序是否存在嵌套的 COALESCE 空值处理。",
          "嵌套空值回退会增加取值优先级核对成本，错误括号或类型推断也可能使查询失败。",
          "读取程序文本并转为大写后，出现 COALESCE(COALESCE( 即触发；不解析函数调用树。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.distinct_review", "python", "加工程序中的 DISTINCT 须核对去重范围", "warn",
          "检查加工程序中的查询是否使用 DISTINCT 去重。",
          "不必要的去重可能增加排序或哈希开销；不恰当的去重也可能掩盖关联产生的重复行。",
          "读取程序文本后，只要大写化文本包含 DISTINCT 即触发；注释和字符串也可能命中。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.legacy_outer_join", "python", "加工程序不得使用 (+) 外连接写法", "err",
          "检查程序文本是否包含 (+) 字符串。",
          "旧式外连接的条件分布不直观，后续修改过滤条件时容易改变保留行的语义。",
          "读取程序文本并转为大写后，出现 (+) 即触发；注释、字符串也可能命中。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.affected_rows_log", "python", "加工程序必须包含影响条数日志", "err",
          "检查加工程序是否记录受影响的数据行数。",
          "没有影响行数记录时，批处理执行后难以从日志确认实际更新或插入的数据量。",
          "当程序文本不含“影响条数”字符串时触发；不验证日志调用是否可执行或是否记录了正确数量。",
          "DWS 加工 Python 文件", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.legacy_group_clause", "python", "加工程序不得包含旧版 GROUP 子句", "err",
          "检查加工程序 SQL 是否使用旧版 GROUP 子句。",
          "旧版 GROUP 语句可能与当前数据库部署约定不兼容，导致建表或执行失败。",
          "程序文本大写化后包含 TO GROUP GROUP_VERSION1 即触发。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.hardcoded_date", "python", "加工程序不得依赖疑似硬编码日期", "err",
          "检查加工程序的 SQL 内容中是否出现疑似固定日期。",
          "固定日期可能使后续批次继续处理旧期间或跳过应处理期间；模式命中本身不能证明日期用途。",
          "当程序文件第 1000 个字符之后的 SQL 内容命中一个或多个日期模式时触发；这是文本启发式。",
          "DWS 加工 Python 文件及其中的 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.use_view", "python", "加工程序引用的视图须重点复核", "err",
          "检查加工程序是否引用已登记的数据库视图。",
          "视图定义或底层数据变化可能改变作业读取的结果集，未登记依赖会使变更影响难以追踪。",
          "仅当视图元数据读取成功，且过滤结果表和内置函数后仍存在与元数据匹配的引用时触发。",
          "DWS 加工 Python 文件及其引用的 SQL 对象", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.use_function", "python", "加工程序调用的数据库函数须重点复核", "err",
          "检查加工程序是否调用已登记的数据库函数。",
          "数据库函数实现变化会影响调用结果或执行开销，未识别的依赖难以随变更核对。",
          "仅当函数元数据可读取，且程序中一个或多个函数调用匹配登记项时触发。",
          "DWS 加工 Python 文件及其引用的 SQL 函数", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.partition_rollback", "python", "分区表状态须与 rollback_deal 步骤一致", "err",
          "比较结果表分区元数据与源文本中 rollback_deal 定义、分区操作模式的组合状态。",
          "分区表在缺少回滚处理时可能留下不完整分区结果；非分区表执行该步骤也可能失败。",
          "当分区元数据可确认且表为分区表状态，与源码中同时出现 rollback_deal 和分区操作的结果不一致时触发。",
          "DWS 加工 Python 文件及其结果表分区元数据", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.missing_schema", "python", "加工程序中的表引用必须带 schema", "err",
          "检查加工程序中引用的业务表是否明确标明所属 schema。",
          "缺少 schema 的引用可能落到错误的默认 schema，或在不同运行账户下解析为不同对象。",
          "在截取文件前 1000 字符后的提取结果中，排除内置名、结果表和已识别函数后，剩余名称不含点号即触发；CTE 等文本可能误命中。",
          "DWS 加工 Python 文件及其 SQL 对象引用", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.forbidden_table", "python", "加工程序不得引用禁用表清单中的表", "err",
          "检查加工程序是否引用已列入禁用清单的表。",
          "继续读取已列入禁用清单的表，可能使用过期或不应再作为来源的数据。",
          "当禁用表清单可读取且其中任一表名（大小写不敏感）出现在程序文本中时触发。",
          "DWS 加工 Python 文件及其表引用", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.scalar_subquery", "python", "加工程序中的标量子查询须确认单行结果", "err",
          "检查去除普通空格和 TAB 后的程序文本是否包含 =(SELECT。",
          "若等号右侧子查询返回多行，数据库会在执行时报告标量子查询错误。",
          "去除普通空格和 TAB 并转为大写后包含 =(SELECT 即触发；不解析查询基数。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.in_subquery", "python", "加工程序中的 IN 子查询须核对扫描范围", "warn",
          "检查去除普通空格和 TAB、并移除 JOIN(SELECT 后的程序文本是否包含 IN(SELECT。",
          "大型子查询可能读取较多数据并增加作业时间；字符串命中不能证明实际扫描量。",
          "归一化后的程序文本包含 IN(SELECT 即触发，不分析执行计划或子查询大小。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.end_dt_range", "python", "拉链表查询须核对 END_DT 上界", "err",
          "检查程序文本是否包含 .END_DT>= 子串。",
          "包含结束日期边界的记录可能与有效期筛选逻辑重叠，造成同一业务对象重复返回。",
          "去除普通空格和 TAB 并转为大写后，出现 .END_DT>= 即触发；不解析字段来源和比较语义。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_to_date", "python", "主题表日期过滤不得对 D_DATE 使用 TO_DATE", "err",
          "检查主题表 SQL 是否使用 TO_DATE 转换 D_DATE。",
          "对分区日期字段套用转换函数可能使约定的日期过滤或分区裁剪不生效。",
          "当共享日期规则检测到 d_date_to_date 模式时触发；检测仅覆盖其识别的文本形态。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_literal", "python", "主题表日期过滤不得使用 DATE 字面量", "err",
          "检查主题表 SQL 是否使用 DATE 字面量比较 D_DATE。",
          "不符合主题表日期约定的字面量可能绕开既定分区筛选方式。",
          "当共享日期规则检测到 d_date_literal 模式时触发；不推断该查询的数据覆盖范围。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_function", "python", "主题表日期过滤不得转换 D_DATE", "err",
          "检查主题表 SQL 是否对 D_DATE 使用 DATE 函数。",
          "对日期分区列执行函数转换可能阻止约定过滤条件直接作用于分区列。",
          "当共享日期规则检测到 d_date_function 模式时触发。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.to_date_d_date", "python", "主题表日期过滤不得转换 D_DATE", "err",
          "检查主题表 SQL 是否将 D_DATE 作为 TO_DATE 的输入。",
          "对日期分区列进行字符串转换可能使过滤表达式偏离主题表的日期约定。",
          "当共享日期规则检测到 to_date_d_date 模式时触发；仅覆盖解析器识别的文本形态。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_less_than", "python", "主题表 D_DATE 范围须符合全量表约定", "err",
          "检查全量主题表 SQL 是否为 D_DATE 设置小于条件。",
          "对按全量方式使用的主题表增加日期下界可能排除所需历史记录。",
          "当共享日期规则检测到 d_date_less_than 模式时触发；不确认对象是否确为全量表。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_greater_than", "python", "主题表 D_DATE 范围须符合全量表约定", "err",
          "检查全量主题表 SQL 是否为 D_DATE 设置大于条件。",
          "对按全量方式使用的主题表增加日期上界可能排除有效记录或批次数据。",
          "当共享日期规则检测到 d_date_greater_than 模式时触发；不确认对象是否确为全量表。",
          "DWS 加工 Python 文件及其 SQL", _HCYT_PY, "rule_dws_py"),

    # HCYT SQL rules and the two active structured asset-issue identities.
    _hcyt("hcyt.sql.create_view", "sql", "DWS SQL 中创建视图须重点复核", "err",
          "检查 DWS SQL 是否包含视图定义。",
          "视图是共享数据库对象，定义变化可能改变其他作业读取的数据集。",
          "当 DWS SQL 中存在一个或多个 CREATE VIEW 定义时触发。",
          "DWS SQL 文件", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.create_function", "sql", "DWS SQL 中创建函数须重点复核", "err",
          "检查 DWS SQL 是否包含函数定义。",
          "数据库函数变化可能影响所有调用方的执行结果或依赖关系。",
          "当 DWS SQL 中存在一个或多个 CREATE FUNCTION 定义时触发。",
          "DWS SQL 文件", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.use_view", "sql", "DWS SQL 引用的视图须重点复核", "err",
          "检查 DWS SQL 是否引用已登记的数据库视图。",
          "视图底层定义或数据来源变化可能改变当前 SQL 的结果集。",
          "仅当视图元数据可读取且提取的名称与其匹配时触发。",
          "DWS SQL 文件及其引用对象", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.use_function", "sql", "DWS SQL 调用的数据库函数须重点复核", "err",
          "检查 DWS SQL 是否调用已登记的数据库函数。",
          "函数实现变化会改变调用方的结果或运行成本，登记依赖有助于审查影响范围。",
          "仅当函数元数据可读取且 detect_used_functions 返回已登记函数时触发。",
          "DWS SQL 文件及其调用函数", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.too_many_lines", "sql", "DWS SQL 文件不得超过 20,000 行", "err",
          "检查按换行符拆分后的 DWS SQL 行数是否大于 20,000。",
          "单文件体量过大时，人工定位变更和审查 SQL 语句的成本明显增加。",
          "当 len(data.split('\\n')) > 20000 时触发；空行也计入行数。",
          "DWS SQL 文件", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.dwm_operation", "sql", "DWS SQL 中的 DWM 引用须重点复核", "warn",
          "检查 DWS SQL 是否涉及 DWM 模型层对象。",
          "对模型层对象的写入或引用可能影响已发布模型和下游报表；文本匹配无法确定具体操作。",
          "当 SQL 文本（含注释或字符串）大小写不敏感地包含 DWM. 时触发。",
          "DWS SQL 文件", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.legacy_group_clause", "sql", "DWS SQL 不得包含旧版 GROUP 子句", "err",
          "检查 DWS SQL 文本是否包含 TO GROUP GROUP_VERSION1。",
          "旧版 GROUP 语句可能与当前数据库部署规则不兼容。",
          "当 SQL 大写文本包含 TO GROUP GROUP_VERSION1 时触发。",
          "DWS SQL 文件", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.manual_code_table_write", "asset_registry", "码值表写操作须与登记信息核对", "warn",
          "检查解析出的写操作目标是否出现在资产平台手工码值表登记中。",
          "直接写入受登记管理的码值表可能绕过其变更维护流程，导致码值定义与登记状态不一致。",
          "仅当码值表元数据可读取，且解析到的 INSERT、UPDATE、DELETE、MERGE、TRUNCATE 或相关 DDL 目标表代码存在于登记中时触发。",
          "DWS SQL 写操作及码值表登记元数据", _HCYT_SQL, "collect_manual_code_table_write_findings"),
    _hcyt("hcyt.sql.legacy_marker", "sql", "DWS SQL 不得包含已配置的遗留取数标记", "err",
          "检查 DWS SQL 是否包含已标记为遗留的取数内容。",
          "遗留取数标记可能表明 SQL 仍引用旧取数对象，执行后会读取错误或过期来源。",
          "将 SQL 转为大写后，命中任一配置 marker 且未命中其 excludes 时触发。",
          "DWS SQL 文件", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.legacy_markers",)),
    _hcyt("hcyt.sql.protected_code_table", "asset_registry", "受保护码值表的 SQL 引用须复核", "err",
          "检查 DWS SQL 是否引用受保护的码值表。",
          "修改受保护码值表可能改变多个作业共享的码值映射或解释结果。",
          "将 SQL 转为大写后，包含任一 configured protected_code_tables 表名即触发；该检测不区分读写操作。",
          "DWS SQL 文件及受保护码值表", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.protected_code_tables",)),
    _hcyt("hcyt.hive.too_many_lines", "sql", "Hive SQL 文件不得超过 20,000 行", "err",
          "检查按换行符拆分后的 Hive SQL 行数是否大于 20,000。",
          "单文件体量过大时，变更审查和问题定位需要在大量文本中搜索。",
          "当 len(data.split('\\n')) > 20000 时触发；空行也计入行数。",
          "Hive SQL 文件", _HCYT_SQL, "rule_hive"),
    _hcyt("hcyt.hive.varchar2_type", "sql", "Hive SQL 不得使用 VARCHAR2 字段类型", "err",
          "检查 Hive SQL 文本是否包含 VARCHAR2 字符串。",
          "VARCHAR2 是特定数据库类型，在 Hive 执行环境中可能无法识别或产生不兼容行为。",
          "当 Hive SQL 大写文本包含 VARCHAR2 时触发；注释和字符串也可能命中。",
          "Hive SQL 文件", _HCYT_SQL, "rule_hive"),
    _hcyt("hcyt.sql.permission_change", "sql", "DWS SQL 中的权限变更须重点复核", "err",
          "检查顶层 SQL 语句是否为 GRANT 或 REVOKE。",
          "权限变更会改变主体对数据或对象的访问范围，错误授权可能暴露数据或阻断作业。",
          "仅当顶层语句命令为 GRANT 或 REVOKE 时触发；注释和字符串会在分词阶段跳过。",
          "DWS SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.identity_change", "sql", "DWS SQL 中的用户或角色变更须重点复核", "err",
          "检查顶层语句是否创建、修改或删除 ROLE / USER。",
          "身份对象变更会改变数据库主体和后续授权的适用范围。",
          "当顶层命令为 CREATE、ALTER 或 DROP，且后续对象类型为 ROLE 或 USER 时触发。",
          "DWS SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.destructive_ddl", "sql", "DWS SQL 中的对象删除须重点复核", "err",
          "检查顶层语句是否删除数据库对象、截断表，或删除表字段/分区。",
          "删除对象、数据或分区可能造成不可逆的数据缺失及下游作业失败。",
          "当解析到 DROP 支持对象、TRUNCATE，或 ALTER TABLE DROP COLUMN / PARTITION 时触发。",
          "DWS SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.unbounded_dml", "sql", "DWS SQL 的 UPDATE / DELETE 须包含 WHERE", "err",
          "检查顶层 UPDATE 或 DELETE 语句是否没有 WHERE token。",
          "无条件修改可能影响目标表全部记录，而非本次预期的数据范围。",
          "当顶层命令为 UPDATE 或 DELETE 且分词后不存在 WHERE 时触发；不计算过滤条件实际选择范围。",
          "DWS SQL 顶层 DML", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.overwrite_write", "sql", "DWS SQL 的覆盖写入须核对目标范围", "warn",
          "检查顶层 INSERT OVERWRITE 或包含 OVERWRITE 的 LOAD 语句。",
          "覆盖写入可能替换目标表或分区中已有数据，范围设置错误会丢失历史结果。",
          "当顶层命令为 INSERT 且第二个 token 是 OVERWRITE，或 LOAD 语句含 OVERWRITE 时触发。",
          "DWS SQL 顶层写入语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.alter_statement", "sql", "DWS SQL 中的 ALTER 语句须重点复核", "warn",
          "检查无法归入身份变更、破坏性操作的顶层 ALTER 语句。",
          "ALTER 会改变数据库对象结构或属性，未经核对可能造成兼容性问题。",
          "当顶层命令为 ALTER 且未先命中身份变更、ALTER TABLE DROP 破坏性分支时触发。",
          "DWS SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.permission_change", "sql", "Hive SQL 中的权限变更须重点复核", "err",
          "检查顶层 Hive SQL 语句是否为 GRANT 或 REVOKE。",
          "权限变更会改变主体对数据或对象的访问范围，错误授权可能暴露数据或阻断作业。",
          "仅当顶层语句命令为 GRANT 或 REVOKE 时触发。",
          "Hive SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.identity_change", "sql", "Hive SQL 中的用户或角色变更须重点复核", "err",
          "检查顶层语句是否创建、修改或删除 ROLE / USER。",
          "身份对象变更会改变数据库主体和后续授权的适用范围。",
          "当顶层命令为 CREATE、ALTER 或 DROP，且对象类型为 ROLE 或 USER 时触发。",
          "Hive SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.destructive_ddl", "sql", "Hive SQL 中的对象删除须重点复核", "err",
          "检查顶层语句是否删除支持的数据库对象、截断表，或删除表字段/分区。",
          "删除对象、数据或分区可能造成数据缺失及依赖作业失败。",
          "当解析到 DROP 支持对象、TRUNCATE，或 ALTER TABLE DROP COLUMN / PARTITION 时触发。",
          "Hive SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.unbounded_dml", "sql", "Hive SQL 的 UPDATE / DELETE 须包含 WHERE", "err",
          "检查顶层 UPDATE 或 DELETE 语句是否没有 WHERE token。",
          "无条件修改可能影响目标表全部记录，而非本次预期的数据范围。",
          "当顶层命令为 UPDATE 或 DELETE 且分词后不存在 WHERE 时触发。",
          "Hive SQL 顶层 DML", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.overwrite_write", "sql", "Hive SQL 的覆盖写入须核对目标范围", "warn",
          "检查顶层 INSERT OVERWRITE 或包含 OVERWRITE 的 LOAD 语句。",
          "覆盖写入可能替换目标表或分区已有数据，范围设置错误会丢失历史结果。",
          "当顶层命令为 INSERT 且第二个 token 是 OVERWRITE，或 LOAD 语句含 OVERWRITE 时触发。",
          "Hive SQL 顶层写入语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.alter_statement", "sql", "Hive SQL 中的 ALTER 语句须重点复核", "warn",
          "检查未被更具体身份变更或破坏性规则命中的顶层 ALTER 语句。",
          "ALTER 会改变数据库对象结构或属性，未经核对可能造成兼容性问题。",
          "当顶层命令为 ALTER 且未命中身份变更或 ALTER TABLE DROP 破坏性分支时触发。",
          "Hive SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("ASSET_TABLE_REVIEW", "asset_registry", "DWM、DWA、DM 建表对象须纳入资产登记核对", "warn",
          "检查新建表是否属于需要纳入资产登记核对的数据层。",
          "未登记的结果表可能无法被资产目录检索或被下游交付关系识别。",
          "当 CREATE TABLE 或加工程序结果表的 schema 在 asset_review_required_schemas 中时生成资产问题；该 ID 保持现有无 workflow 前缀形式。",
          "DWS 建表语句或加工程序结果表", _HCYT_SQL, "collect_created_table_review_issues",
          ("dws.naming.asset_review_required_schemas",),
          (RuleImplementation(_HCYT_PY, "build_asset_table_review_issues"),
           RuleImplementation(_HCYT_DDL, "is_asset_review_required_table"))),
    _hcyt("ROOT_MISSING", "asset_registry", "表和字段名称词根须登记", "warn",
          "检查表名和字段名使用的词根是否已在资产词根库登记。",
          "未登记的词根无法按统一词汇检索和解释，降低资产名称的可发现性。",
          "仅当词根元数据可读取且 schema 在 root_check_required_schemas 中时，对每个缺失词段生成问题；该 ID 保持现有无 workflow 前缀形式。",
          "DWS 表名或字段名", _HCYT_DDL, "collect_root_missing_issues",
          ("dws.naming.root_check_required_schemas", "dws.naming.schema_prefixes",
           "dws.naming.temporary_table_prefixes")),

    # HCYT schedule inventory; generated IDs enumerate the current DWD/DWP/DWM config keys.
    _hcyt("hcyt.schedule.plan.invalid_name", "schedule", "计划名不得使用已禁用名称", "err",
          "检查上线计划名是否精确匹配 invalid_plan_names 中的值。",
          "沿用已禁用计划名可能覆盖或混淆现有生产调度对象。",
          "当计划表中非空计划名与配置禁用名称完全相等时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.invalid_plan_names",)),
    _hcyt("hcyt.schedule.plan.dwd_name", "schedule", "DWD 计划名必须匹配允许名称", "err",
          "检查名称含 DWD 关键字的计划是否属于配置的 DWD 允许名称。",
          "同层计划命名不一致会使运行人员难以判断计划用途，并可能造成调度对象重复。",
          "当计划名包含 DWD 且不在 plan_name_rules.DWD 列表中时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.plan_name_rules.DWD",)),
    _hcyt("hcyt.schedule.plan.dwp_name", "schedule", "DWP 计划名必须匹配允许名称", "err",
          "检查名称含 DWP 关键字的计划是否属于配置的 DWP 允许名称。",
          "同层计划命名不一致会使运行人员难以判断计划用途，并可能造成调度对象重复。",
          "当计划名包含 DWP 且不在 plan_name_rules.DWP 列表中时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.plan_name_rules.DWP",)),
    _hcyt("hcyt.schedule.plan.dwm_name", "schedule", "DWM 计划名必须匹配允许名称", "err",
          "检查名称含 DWM 关键字的计划是否属于配置的 DWM 允许名称。",
          "同层计划命名不一致会使运行人员难以判断计划用途，并可能造成调度对象重复。",
          "当计划名包含 DWM 且不在 plan_name_rules.DWM 列表中时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.plan_name_rules.DWM",)),
    _hcyt("hcyt.schedule.plan.predecessor", "dependency", "计划不得登记未核对的前置计划", "warn",
          "检查 PLAN 行的前置依赖列是否非空。",
          "未核对的计划级依赖可能形成多余等待或使计划执行顺序偏离实际生产关系。",
          "当 PLAN 行第二列的依赖文本非空时触发；不判断依赖对象是否存在或是否必要。",
          "HCYT PLAN 行", _HCYT_SCHEDULE, "rule_excle_plan"),
    _hcyt("hcyt.schedule.plan.upstream_registration", "asset_registry", "接入计划名须登记为上游系统", "err",
          "检查接入计划前缀对应的名称是否存在于上游系统登记元数据。",
          "缺少上游登记会使接入来源无法与资产平台中的系统实体关联。",
          "仅当计划名以 recv_mapping_plan_prefix 开头且不在可读取的上游系统 ID 集合中时触发。",
          "HCYT PLAN 行及上游系统登记", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.recv_mapping_plan_prefix",)),
    _hcyt("hcyt.schedule.plan.missing_send_plan", "metadata", "SEND 作业对应计划须存在于生产", "warn",
          "检查未匹配生产计划的上线计划是否关联到已识别的 SEND 作业。",
          "SEND 作业已进入上线包但生产计划不存在时，调度关系可能无法按预期发布。",
          "当计划名不在 all_plan 元数据中且其大写形式属于从 SEND 作业提取的计划集合时触发。",
          "HCYT PLAN 行及生产计划元数据", _HCYT_SCHEDULE, "rule_excle_plan"),
    _hcyt("hcyt.schedule.plan.missing_dws_plan", "metadata", "DWS 加工计划须存在于生产", "warn",
          "检查未匹配生产计划的计划名是否符合配置的 DWS 计划前后缀模式。",
          "缺少生产计划登记会使上线计划无法对应到既有生产调度实体。",
          "当计划名不在 all_plan 元数据中、不是 SEND 计划，且匹配 missing_plan_warning_patterns 的首个模式时触发。",
          "HCYT PLAN 行及生产计划元数据", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.missing_plan_warning_patterns",)),
    _hcyt("hcyt.schedule.plan.missing_production_plan", "metadata", "上线计划须存在于生产", "warn",
          "检查计划名是否存在于生产计划元数据。",
          "生产中没有对应计划时，新作业可能无法挂接到可执行的调度计划。",
          "当计划名不在 all_plan 元数据中，且未命中 SEND 或指定 DWS 计划分支时触发。",
          "HCYT PLAN 行及生产计划元数据", _HCYT_SCHEDULE, "rule_excle_plan"),
    _hcyt("hcyt.schedule.seq.realtime_override", "schedule", "作业流不得覆盖生产实时作业流", "err",
          "检查上线 SEQ 名称是否与生产实时作业流元数据中的名称相同。",
          "同名上线作业流可能覆盖生产实时作业流的调度配置。",
          "当 SEQ 第一列名称出现在 all_real_seq 元数据集合中时触发。",
          "HCYT SEQ 调度表及生产实时作业流元数据", _HCYT_SCHEDULE, "rule_excle_seq"),
    _hcyt("hcyt.schedule.seq.invalid_calendar", "schedule", "作业流日历必须存在于日历元数据", "err",
          "检查 SEQ 执行日历是否存在于生产日历名称集合。",
          "无效日历会使作业流无法按预定日期运行或被调度系统拒绝。",
          "当 SEQ 日历非空、日历元数据集合非空且名称不匹配任何日历时触发。",
          "HCYT SEQ 调度表及生产日历元数据", _HCYT_SCHEDULE, "rule_excle_seq"),
    _hcyt("hcyt.schedule.job.invalid_schema", "schedule", "JOB 调度表必须至少包含 28 列", "err",
          "检查 JOB 数据表的列数是否达到依赖字段所在位置所需的最小数量。",
          "列数不足时规则会把其他字段读作错误列，导致后续调度判断失真。",
          "当 JOB 数据为空或列数小于 28 时触发，并提前结束该 JOB 表检查。",
          "HCYT JOB Excel", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.dependency_cycle", "dependency", "上线作业依赖不得形成循环", "err",
          "检查上线作业依赖图中是否存在闭环路径。",
          "循环依赖中的作业会互相等待，导致调度无法找到可执行的起点。",
          "根据上线作业依赖和可用生产依赖构图后，find_cycles 在上线作业节点范围内返回一个或多个环时触发。",
          "HCYT JOB 依赖列及生产作业依赖元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.lowercase_job", "schedule", "JOB 名称必须使用大写字母", "err",
          "检查 JOB 单元格文本是否与其大写形式相同。",
          "大小写不一致可能使作业名与生产登记或依赖配置中的名称无法匹配。",
          "当 JOB 名非空且 job_name.upper() != job_name 时触发。",
          "HCYT JOB Excel 的 JOB 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.lowercase_plan", "schedule", "计划名称必须使用大写字母", "err",
          "检查 JOB 行关联的计划名单元格是否与其大写形式相同。",
          "大小写不一致可能使计划与生产元数据或计划命名规则匹配失败。",
          "当计划名单元格非空且其大写形式与原值不同时触发。",
          "HCYT JOB Excel 的 PLAN 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.lowercase_sequence", "schedule", "作业流名称必须使用大写字母", "err",
          "检查 JOB 行关联的作业流名单元格是否与其大写形式相同。",
          "大小写不一致可能使作业流与生产归属或日历元数据匹配失败。",
          "当作业流名单元格非空且其大写形式与原值不同时触发。",
          "HCYT JOB Excel 的 SEQ 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.disabled_reenable", "metadata", "生产禁用作业不得被意外重新启用", "err",
          "比较上线 JOB 与生产作业状态，检查目标作业是否登记为禁用。",
          "意外重新启用的作业可能恢复已停用的数据处理或下游推送。",
          "当 JOB 名存在于生产状态映射且状态被识别为“禁用”时触发。",
          "HCYT JOB Excel 及生产作业状态元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.disabled_status_values", "hcyt.schedule.enabled_status_values")),
    _hcyt("hcyt.schedule.job.empty_sequence", "schedule", "JOB 必须登记所属作业流", "err",
          "检查 JOB 行的 SEQ 单元格是否为空字符串。",
          "没有作业流归属的 JOB 可能无法按计划执行，也难以与生产调度结构核对。",
          "当去除首尾空格后的 SEQ 值为空时触发。",
          "HCYT JOB Excel 的 SEQ 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.realtime_priority", "schedule", "实时作业优先级必须为 99", "err",
          "检查实时作业流或名称包含实时关键字的 JOB，其优先级是否属于配置允许值。",
          "优先级不符合实时约定可能使实时作业排队晚于预期。",
          "当 SEQ 属于生产实时序列或包含配置关键字，且优先级不在 realtime_priority_values 中时触发。",
          "HCYT JOB Excel 的 SEQ / JOB / PRIORITY 列及实时序列元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.real_job_plan_names", "hcyt.schedule.realtime_sequence_keyword",
           "hcyt.schedule.realtime_priority_values")),
    _hcyt("hcyt.schedule.job.description", "schedule", "作业描述必须包含有效加工说明", "err",
          "按配置的最少中文字符、噪声短语和无效值规则判断 JOB 描述是否有实质内容。",
          "描述不足时，审核人员无法从调度表判断作业用途及其处理范围。",
          "当 has_meaningful_job_description 对描述、作业名和配置返回 false 时触发。",
          "HCYT JOB Excel 的 DESCRIPTION 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.description_validation",)),
    _hcyt("hcyt.schedule.job.realtime_calendar", "schedule", "指定实时计划必须使用每日执行日历", "err",
          "检查指定实时计划的 JOB 日历是否等于配置的实时日历值。",
          "日历不匹配会使实时作业漏跑或按非预期频率执行。",
          "当 PLAN 名在 realtime_calendar_plans 中且 JOB 日历不等于 realtime_calendar_value 时触发。",
          "HCYT JOB Excel 的 PLAN / CALENDAR 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.realtime_calendar_plans", "hcyt.schedule.realtime_calendar_value")),
    _hcyt("hcyt.schedule.job.invalid_calendar", "metadata", "JOB 执行日历必须存在于日历元数据", "err",
          "检查非空 JOB 日历是否存在于生产日历名称集合。",
          "调度系统无法识别的日历可能使作业不运行或被分配错误的运行日期。",
          "当有效日历元数据非空且 JOB 日历不在集合中时触发；元数据集合为空时跳过此判断。",
          "HCYT JOB Excel 的 CALENDAR 列及生产日历元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.execution_domain", "schedule", "指定计划的作业不得使用禁用执行域", "err",
          "检查执行域是否等于禁用域，且计划名包含配置的禁用计划关键字。",
          "在这些计划中使用禁用执行域可能使作业提交到错误的运行环境。",
          "当 domain == forbidden_domain 且 plan_name 命中任一 forbidden_domain_plan_keywords 时触发。",
          "HCYT JOB Excel 的 PLAN / DOMAIN 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_domain", "hcyt.schedule.forbidden_domain_plan_keywords")),
    _hcyt("hcyt.schedule.job.invalid_domain", "schedule", "作业执行域必须属于允许列表", "err",
          "检查 JOB 执行域是否包含在 configured allowed_domains 中。",
          "未受支持的执行域可能使作业调度到不存在或未授权的运行环境。",
          "当 JOB 的 DOMAIN 值不属于 allowed_domains 时触发。",
          "HCYT JOB Excel 的 DOMAIN 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.allowed_domains",)),
    _hcyt("hcyt.schedule.job.dwd_sequence", "schedule", "DWD 计划须使用允许的作业流名", "err",
          "检查 DWD 计划下的 SEQ 是否属于配置的 DWD 作业流名称。",
          "作业流与计划层级不一致会使任务进入错误批次或无法按层级维护。",
          "当 PLAN 包含 DWD 且 SEQ 不在 sequence_name_rules.DWD 中时触发。",
          "HCYT JOB Excel 的 PLAN / SEQ 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.sequence_name_rules.DWD",)),
    _hcyt("hcyt.schedule.job.dwp_sequence", "schedule", "DWP 计划须使用允许的作业流名", "err",
          "检查 DWP 计划下的 SEQ 是否属于配置的 DWP 作业流名称。",
          "作业流与计划层级不一致会使任务进入错误批次或无法按层级维护。",
          "当 PLAN 包含 DWP 且 SEQ 不在 sequence_name_rules.DWP 中时触发。",
          "HCYT JOB Excel 的 PLAN / SEQ 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.sequence_name_rules.DWP",)),
    _hcyt("hcyt.schedule.job.dwm_sequence", "schedule", "DWM 计划须使用允许的作业流名", "err",
          "检查 DWM 计划下的 SEQ 是否属于配置的 DWM 作业流名称。",
          "作业流与计划层级不一致会使任务进入错误批次或无法按层级维护。",
          "当 PLAN 包含 DWM 且 SEQ 不在 sequence_name_rules.DWM 中时触发。",
          "HCYT JOB Excel 的 PLAN / SEQ 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.sequence_name_rules.DWM",)),
    _hcyt("hcyt.schedule.job.missing_dwf_dependency", "dependency", "DWF 加工作业必须填写前置依赖", "err",
          "检查 JOB 名是否包含 DWF 加工作业关键字，并检查依赖字段是否为空。",
          "没有前置输入依赖的 DWF 作业可能在来源数据尚未就绪时启动。",
          "当依赖文本为空且 JOB 名包含 dependency_required_job_keywords 的第一个关键字时触发。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.dependency_required_job_keywords",)),
    _hcyt("hcyt.schedule.job.missing_dwo_dependency", "dependency", "DWO 加工作业必须填写前置依赖", "err",
          "检查无依赖的 JOB 名是否包含 DWO 加工作业关键字。",
          "DWO 作业在来源表或上游作业未完成时启动，可能读取不完整数据。",
          "当依赖文本为空、JOB 名未命中首个 DWF 关键字及例外，且命中 DWO 关键字时触发。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.dependency_required_job_keywords", "hcyt.schedule.dependency_exceptions")),
    _hcyt("hcyt.schedule.job.missing_dependency", "dependency", "指定层级作业必须填写前置依赖", "err",
          "检查无依赖的 JOB 名是否命中配置中的 DWP、DWM、DWA、SEND、LOCAL 等关键字。",
          "缺少上游依赖可能使作业在必需数据未准备时运行。",
          "当依赖文本为空、JOB 名未命中更早的 DWF/DWO 分支及配置例外，并命中后续必需关键字时触发。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.dependency_required_job_keywords", "hcyt.schedule.dependency_exceptions")),
    _hcyt("hcyt.schedule.job.chinese_dependency_colon", "dependency", "作业依赖不得使用中文冒号", "err",
          "检查 DEPENDENCIES 单元格是否包含中文全角冒号。",
          "依赖解析按半角分隔符拆分时，全角冒号可能使作业名无法提取和匹配。",
          "当 DEPENDENCIES 文本包含字符“：”时触发。",
          "HCYT JOB Excel 的 DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.provision_dependency", "dependency", "指定执行域的加工 JOB 不得依赖卸数 JOB", "err",
          "检查指定执行域作业的依赖项是否包含配置的卸数作业关键字。",
          "加工任务直接依赖卸数任务可能绕过预期的数据装载与加工顺序。",
          "当当前作业 DOMAIN 等于 forbidden_domain 且任一解析出的前置 JOB 包含 provision_job_keyword 时触发。",
          "HCYT JOB Excel 的 DOMAIN / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_domain", "hcyt.schedule.provision_job_keyword")),
    _hcyt("hcyt.schedule.job.missing_production_dependency", "dependency", "作业前置依赖必须存在于生产或上线清单", "err",
          "检查解析出的前置 JOB 名是否存在于生产作业或当前上线作业集合。",
          "引用不存在的前置作业会使调度等待一个永远不会完成的节点。",
          "当非空前置 JOB 不在 yilai_job 集合中时触发；该集合由生产元数据和当前作业名组成。",
          "HCYT JOB Excel 及生产作业元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.self_dependency", "dependency", "作业不得依赖自身或所属计划", "err",
          "检查解析出的前置 JOB 标识是否等于当前 JOB 名或计划名。",
          "自依赖或将计划名误写为作业依赖会造成依赖图错误或循环等待。",
          "当任一解析出的 job_real 与 job_name 或 plan_name 相等时触发。",
          "HCYT JOB Excel 的 JOB / PLAN / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.realtime_plan_dependency", "dependency", "实时计划不得依赖普通计划作业", "err",
          "比较实时计划的前置作业所属计划是否也具有实时后缀。",
          "实时任务等待普通批次计划可能错过预期的实时出数时间。",
          "当当前计划以 realtime_plan_suffix 结尾，前置 JOB 与所属计划均可解析，且前置计划不以该后缀结尾时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.realtime_plan_suffix",)),
    _hcyt("hcyt.schedule.job.late_plan_dependency", "dependency", "作业不得依赖未豁免的晚执行计划", "warn",
          "检查前置作业的生产所属计划是否在晚执行计划名单中。",
          "上游计划启动较晚可能使当前作业无法在要求的出数时点前完成。",
          "当前计划不在 late_plan_exceptions 且前置计划属于 late_plan_names 时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.late_plan_names", "hcyt.schedule.late_plan_exceptions")),
    _hcyt("hcyt.schedule.job.forbidden_realtime_dependency", "dependency", "普通作业不得依赖禁用实时计划", "err",
          "检查前置作业所属计划是否等于配置的第一个禁止依赖计划。",
          "依赖特殊实时计划可能使普通批次与特定业务调度相互耦合。",
          "当前计划不等于 realtime_dependency_exception 且前置计划等于 forbidden_dependency_plans[0] 时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.realtime_dependency_exception", "hcyt.schedule.forbidden_dependency_plans")),
    _hcyt("hcyt.schedule.job.forbidden_legacy_dependency", "dependency", "作业不得依赖指定旧绩效计划", "err",
          "检查前置作业所属计划是否等于配置的第二个禁止依赖计划。",
          "继续依赖已指定的旧绩效计划会使新作业受旧批次状态和数据口径影响。",
          "当前置计划等于 forbidden_dependency_plans[1] 时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_dependency_plans",)),
    _hcyt("hcyt.schedule.job.missing_production_plan", "metadata", "JOB 所属计划必须存在于生产", "err",
          "检查 JOB 行的计划名是否出现在生产计划列表。",
          "生产中没有对应计划时，JOB 可能无法发布到可执行的调度容器。",
          "当 plan_name 不在当前生产计划列表 r_plan 中时触发。",
          "HCYT JOB Excel 及生产计划元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.parameter_space", "schedule", "指定卸数域的 JOB 参数不得含空格", "err",
          "检查指定执行域 JOB 的参数文本是否包含 ASCII 空格。",
          "参数解析器可能将空格切分为多个参数，导致过滤条件或路径值被错误解释。",
          "当 DOMAIN 等于 forbidden_domain 且参数文本包含普通空格时触发。",
          "HCYT JOB Excel 的 DOMAIN / PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_domain",)),
    _hcyt("hcyt.schedule.job.parameter_tab", "schedule", "JOB 参数不得含 TAB 字符", "err",
          "检查 JOB 参数字段是否包含 TAB 字符。",
          "TAB 可能使调度参数解析结果与表格中看到的内容不一致。",
          "当 PARAMETERS 单元格包含任意制表符时触发，不限于指定执行域。",
          "HCYT JOB Excel 的 PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.duplicate_export_path", "schedule", "卸数路径不得与其他 JOB 重复", "err",
          "从卸数参数中提取 outfile，并与生产 JOB 的 outfile 映射比较。",
          "多个作业写入同一路径可能相互覆盖，使下游读取到错误作业生成的文件。",
          "当计划名包含 recv_plan_keyword、参数含 outfile= 且生产映射显示该路径归属其他 JOB 时触发。",
          "HCYT JOB Excel 的 PLAN / PARAMETERS 列及生产 outfile 元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.recv_plan_keyword",)),
    _hcyt("hcyt.schedule.job.export_flags", "schedule", "卸数参数不得启用全字段或源数据获取标记", "err",
          "检查指定卸数计划的参数是否包含 selflg=N 或 metaflg=Y。",
          "不符合约定的字段/源数据选项可能扩大导出内容或改变卸数接口语义。",
          "当计划名包含 recv_plan_keyword 且参数包含任一指定字面量时触发。",
          "HCYT JOB Excel 的 PLAN / PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.recv_plan_keyword",)),
    _hcyt("hcyt.schedule.job.full_export", "schedule", "DIDP 卸数 JOB 须明确限定导出范围", "warn",
          "检查指定 DIDP 版本文本是否出现，且参数中同时缺少 srcfile 和 -filt。",
          "没有可识别过滤或来源参数的导出可能一次读取过多数据。",
          "当 PROGRAM 包含 DIDP_DATA_PROVISION.1.0 且 PARAMETERS 不含 srcfile 与 -filt 时触发；按文本判断。",
          "HCYT JOB Excel 的 PROGRAM / PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.production_plan_mismatch", "metadata", "JOB 计划归属须与生产一致", "err",
          "比较上线 JOB 的计划名与生产中同名 JOB 的计划归属。",
          "改变已有 JOB 的计划归属可能使其进入不同批次并影响执行顺序。",
          "当 JOB 存在于生产、SEQ 不为 0 且生产计划名与上线计划名不同时触发。",
          "HCYT JOB Excel 及生产 JOB 计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.production_sequence_mismatch", "metadata", "JOB 作业流归属须与生产一致", "err",
          "比较上线 JOB 的 SEQ 与生产中同名 JOB 的作业流归属。",
          "改变已有 JOB 的作业流归属可能使其按不同日历或调度顺序执行。",
          "当 JOB 存在于生产、SEQ 不为 0 且生产作业流与上线作业流不同时触发。",
          "HCYT JOB Excel 及生产 JOB 作业流元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.sequence_plan_mismatch", "metadata", "作业流计划归属须与生产一致", "err",
          "比较上线 JOB 所用 SEQ 在生产中的所属计划与当前计划名。",
          "将已有作业流挂到不同计划可能改变该作业流下所有 JOB 的运行时点。",
          "当 SEQ 存在于生产、SEQ 不为 0 且其生产计划名与上线计划名不同时触发。",
          "HCYT JOB Excel 及生产 SEQ 计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.required_predecessors", "dependency", "指定 JOB 需复核配置要求的前置作业", "err",
          "检查指定 JOB 是否需要复核其前置作业关系。",
          "若指定 JOB 缺少其业务所需来源作业，可能在输入数据尚未准备时执行。",
          "当 JOB 名命中配置的指定作业键时触发；当前实现不比较依赖列是否包含配置的前置 JOB 列表。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.required_predecessors",)),
    _hcyt("hcyt.schedule.job.push_job_missing", "asset_registry", "SEND 作业必须登记下游推送关系", "warn",
          "检查识别为 SEND 类型的 JOB 是否存在下游推送作业登记。",
          "作业产出成功并不代表下游交付关系已登记；缺少登记会使接收方不在正式交付链路中。",
          "当 SEND 参数识别成功、下游推送元数据可读取，且登记中找不到对应 job_code 时触发。",
          "HCYT SEND JOB 及下游推送登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),
    _hcyt("hcyt.schedule.job.push_job_disabled", "asset_registry", "SEND 作业的下游推送登记必须启用", "warn",
          "检查匹配的下游推送作业登记中是否至少有一条状态为启用。",
          "登记已停用时，作业运行结果不会按该登记关系交付给下游系统。",
          "当 SEND JOB 找到登记记录，但所有匹配记录的状态都不是 Y 时触发。",
          "HCYT SEND JOB 及下游推送登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),
    _hcyt("hcyt.schedule.job.push_system_missing", "asset_registry", "SEND 作业必须登记有效下游系统", "warn",
          "检查匹配的下游推送登记是否都具有非空下游系统代码。",
          "没有系统代码的登记无法确定数据交付对象。",
          "当匹配登记记录中至少有一条 system_code 为空时触发。",
          "HCYT SEND JOB 及下游推送系统登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),
    _hcyt("hcyt.schedule.job.push_system_disabled", "asset_registry", "SEND 作业关联的下游系统必须启用", "warn",
          "检查具有非空系统代码的匹配记录中是否至少存在一条 enabled 系统状态。",
          "所有关联系统均停用时，推送登记无法将作业结果交付到可用接收方。",
          "当存在有效系统代码，但所有有效记录的状态均不为 enabled 时触发。",
          "HCYT SEND JOB 及下游系统登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),

    # NUPS rules. The SQL patterns remain workflow-specific even when their wording resembles HCYT.
    _nups("nups.ddl.temp_table_name", "ddl", "临时表名必须使用 TMP_ 前缀", "err",
          "检查 SQL DDL 或加工程序结果表中的临时表名是否以 TMP_ 开头。",
          "临时对象未使用约定前缀，可能被误认为持久业务表或无法按临时表约定管理。",
          "当对象属于临时表或 TMP schema，且名称不以 DWS_TEMP_TABLE_PREFIXES 中任一前缀开头时触发。",
          "NUPS SQL DDL 或加工程序结果表", _NUPS, "check_table_name_rule",
          ("nups.file_rules.program_table_name.directory_schema_prefix",)),
    _nups("nups.ddl.table_name", "ddl", "分层表名必须符合 schema 前缀", "err",
          "检查已配置分层 schema 的表名是否使用该层对应的固定前缀。",
          "表名层级与前缀不一致会使维护人员和下游作业难以识别其数据层。",
          "当表名 schema 存在于 DWS_TABLE_PREFIX_RULES 且表名不以该 schema 的允许前缀开头时触发。",
          "NUPS SQL DDL 或加工程序结果表", _NUPS, "check_table_name_rule",
          ("nups.file_rules.program_table_name.directory_schema_prefix",)),
    _nups("nups.ddl.column_comment", "ddl", "指定分层表的字段必须有注释", "err",
          "检查必需 schema 中的字段是否具有行内 COMMENT 或对应 COMMENT ON COLUMN。",
          "没有字段说明时，下游使用者无法确认字段含义，容易误用或重复解释字段。",
          "当 schema 属于 COLUMN_COMMENT_REQUIRED_SCHEMAS 且两种注释位置均为空时触发。",
          "NUPS CREATE TABLE / ALTER TABLE 字段定义", _NUPS, "check_column_comment_rule"),
    _nups("nups.sql.create_view", "sql", "NUPS SQL 中创建视图须重点复核", "err",
          "检查 NUPS SQL 是否包含视图定义。",
          "视图定义会新增或改变共享数据库对象，可能影响其他调用方的查询结果。",
          "当 detect_created_views 返回一个或多个对象时触发。",
          "NUPS SQL 文件", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.create_function", "sql", "NUPS SQL 中创建函数须重点复核", "err",
          "检查 NUPS SQL 是否包含函数定义。",
          "数据库函数变化可能影响所有调用方的结果或依赖关系。",
          "当 detect_created_functions 返回一个或多个对象时触发。",
          "NUPS SQL 文件", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.use_view", "sql", "NUPS SQL 引用的视图须重点复核", "err",
          "检查 NUPS SQL 是否引用已登记的数据库视图。",
          "视图定义或底层来源变化可能改变 NUPS 查询的结果集。",
          "仅当视图元数据可读取且提取引用命中已登记视图时触发。",
          "NUPS SQL 文件及其引用对象", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.use_function", "sql", "NUPS SQL 调用的数据库函数须重点复核", "err",
          "检查 NUPS SQL 是否调用已登记的数据库函数。",
          "函数实现变化可能改变调用结果或运行成本，未核对的依赖容易造成回归。",
          "仅当函数元数据可读取且 detect_used_functions 返回已登记函数时触发。",
          "NUPS SQL 文件及其调用函数", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.too_many_lines", "sql", "NUPS SQL 文件不得超过 20,000 行", "err",
          "检查按换行符拆分后的 NUPS SQL 行数是否大于 20,000。",
          "单文件体量过大时，审查变更和定位问题需要在大量文本中搜索。",
          "当 len(data.split('\\n')) > 20000 时触发；空行也计入行数。",
          "NUPS SQL 文件", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.alter_statement", "sql", "NUPS SQL 中的 ALTER 语句须重点复核", "err",
          "检查 NUPS SQL 全文是否包含 ALTER 子串。",
          "ALTER 会改变数据库对象结构或属性，未经核对可能造成兼容性问题。",
          "当 SQL 大写文本包含 ALTER 时触发；该检查不解析语句边界，注释和字符串也可能命中。",
          "NUPS SQL 文件", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.dwm_operation", "sql", "NUPS SQL 中的 DWM 引用须重点复核", "err",
          "检查 NUPS SQL 是否涉及 DWM 模型层对象。",
          "模型层对象变更或引用可能影响已发布模型和下游报表；文本匹配无法区分读写操作。",
          "当 SQL 大写文本（含注释或字符串）包含 DWM. 时触发。",
          "NUPS SQL 文件", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.legacy_group_clause", "sql", "NUPS SQL 不得包含旧版 GROUP 子句", "err",
          "检查 NUPS SQL 文本是否包含 TO GROUP GROUP_VERSION1。",
          "旧版 GROUP 语句可能与当前数据库部署规则不兼容。",
          "当 SQL 大写文本包含 TO GROUP GROUP_VERSION1 时触发。",
          "NUPS SQL 文件", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.legacy_marker", "sql", "NUPS SQL 不得包含已配置的遗留取数标记", "err",
          "检查 NUPS SQL 是否包含已标记为遗留的取数内容。",
          "遗留取数标记可能表明 SQL 仍引用旧取数对象，执行后会读取错误或过期来源。",
          "将 SQL 转为大写后，命中任一配置 marker 且未命中其 excludes 时触发。",
          "NUPS SQL 文件", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.legacy_markers",)),
    _nups("nups.sql.protected_code_table", "asset_registry", "受保护码值表的 SQL 引用须复核", "err",
          "检查 NUPS SQL 是否引用受保护的码值表。",
          "修改受保护码值表可能改变多个作业共享的码值映射或解释结果。",
          "将 SQL 转为大写后，包含任一 protected_code_tables 表名即触发；不区分读写操作。",
          "NUPS SQL 文件及受保护码值表", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.protected_code_tables",)),
    _nups("nups.program.create_view", "python", "报送程序中的视图定义须重点复核", "err",
          "检查 NUPS 加工程序中的 SQL 是否包含视图定义。",
          "视图定义会新增或改变共享数据库对象，可能影响其他调用方的查询结果。",
          "当 detect_created_views 返回一个或多个对象时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.create_function", "python", "报送程序中的函数定义须重点复核", "err",
          "检查 NUPS 加工程序中的 SQL 是否包含函数定义。",
          "数据库函数变化可能影响所有调用方的结果或依赖关系。",
          "当 detect_created_functions 返回一个或多个对象时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.for_loop", "python", "报送程序不得包含 FOR I IN 文本模式", "err",
          "检查程序文本大写化后是否包含 FOR I IN 子串。",
          "被识别为批内循环的逻辑可能重复执行查询或写入并延长作业时间。",
          "当程序源文本包含连续文本 FOR I IN 时触发；不判断其是否为实际 Python 循环。",
          "NUPS Python 加工文件", _NUPS, "rule_dws_py"),
    _nups("nups.program.character_varying_length", "python", "报送程序不得声明定长 CHARACTER VARYING", "err",
          "检查程序文本大写化后是否包含 CHARACTER VARYING(。",
          "固定字符串长度可能无法容纳较长值，导致写入截断或失败。",
          "出现 CHARACTER VARYING( 即触发；不解析列定义。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.varchar2_length", "python", "报送程序不得声明定长 VARCHAR2", "err",
          "检查程序文本大写化后是否包含 VARCHAR2(。",
          "固定字符串长度可能无法容纳较长值，导致写入截断或失败。",
          "出现 VARCHAR2( 即触发；不解析列定义。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.nested_nvl", "python", "报送程序不得嵌套调用 NVL", "err",
          "检查程序文本大写化后是否包含 NVL(NVL(。",
          "多层空值回退会使最终取值路径难以核对，并可能隐藏错误默认值。",
          "出现 NVL(NVL( 即触发；不解析函数调用树。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.nested_coalesce", "python", "报送程序不得嵌套调用 COALESCE", "err",
          "检查程序文本大写化后是否包含 COALESCE(COALESCE(。",
          "嵌套空值回退增加取值优先级核对成本，错误括号或类型推断也可能使查询失败。",
          "出现 COALESCE(COALESCE( 即触发；不解析函数调用树。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.distinct_review", "python", "报送程序中的 DISTINCT 须核对去重范围", "err",
          "检查程序文本是否包含 DISTINCT 字符串，不判断去重是否必要。",
          "不必要的去重可能增加排序或哈希开销；不恰当的去重也可能掩盖关联产生的重复行。",
          "程序文本大写化后包含 DISTINCT 即触发；注释和字符串也可能命中。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.legacy_outer_join", "python", "报送程序不得使用 (+) 外连接写法", "err",
          "检查程序文本是否包含 (+) 字符串。",
          "旧式外连接条件分布不直观，后续修改过滤条件时容易改变保留行的语义。",
          "程序文本包含 (+) 即触发；注释和字符串也可能命中。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.affected_rows_log", "python", "报送程序必须包含影响条数日志", "err",
          "检查程序文本是否包含“影响条数”文本。",
          "缺少影响行数记录时，执行后难以从日志确认实际更新或插入的数据量。",
          "当源文本不含“影响条数”时触发；不验证日志调用是否执行或数量是否准确。",
          "NUPS Python 加工文件", _NUPS, "rule_dws_py"),
    _nups("nups.program.legacy_group_clause", "python", "报送程序不得包含旧版 GROUP 子句", "err",
          "检查程序文本是否包含 TO GROUP GROUP_VERSION1。",
          "旧版 GROUP 语句可能与当前数据库部署规则不兼容。",
          "程序文本大写化后包含 TO GROUP GROUP_VERSION1 时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.hardcoded_date", "python", "报送程序不得依赖疑似硬编码日期", "err",
          "检查报送程序 SQL 内容中是否出现疑似固定日期。",
          "固定日期可能使后续批次处理错误期间；模式命中本身不能证明日期用途。",
          "find_hardcoded_dates(data[1000:]) 返回候选时触发；这是文本启发式。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.use_view", "python", "报送程序引用的视图须重点复核", "err",
          "检查 NUPS 加工程序是否引用已登记的数据库视图。",
          "视图定义或来源变化可能改变报送结果集，未识别的依赖会增加回归风险。",
          "仅当视图元数据可读取且提取对象名命中已登记视图时触发。",
          "NUPS Python 加工文件及其 SQL 对象", _NUPS, "rule_dws_py"),
    _nups("nups.program.use_function", "python", "报送程序调用的数据库函数须重点复核", "err",
          "检查 NUPS 加工程序是否调用已登记的数据库函数。",
          "函数实现变化可能改变报送结果或运行成本。",
          "仅当函数元数据可读取且 detect_used_functions 返回已登记函数时触发。",
          "NUPS Python 加工文件及其 SQL 函数", _NUPS, "rule_dws_py"),
    _nups("nups.program.partition_rollback", "python", "分区表状态须与 rollback_deal 步骤一致", "err",
          "比较结果表分区元数据与源码中 rollback_deal 定义、分区操作模式。",
          "分区表缺少回滚处理可能留下不完整结果；非分区表执行该步骤也可能失败。",
          "结果表名可解析时，若分区元数据状态与源码分区回滚模式不同即触发。",
          "NUPS Python 加工文件及结果表分区元数据", _NUPS, "rule_dws_py"),
    _nups("nups.program.missing_schema", "python", "报送程序中的表引用必须带 schema", "err",
          "检查从程序内容提取的候选表名是否缺少点分隔 schema。",
          "缺少 schema 的引用可能依赖运行账户的默认 schema，造成环境间对象解析不同。",
          "去除内置名称、结果表和函数名后，提取对象不含点号即触发；CTE 等文本可能误命中。",
          "NUPS Python 加工文件及其中的 SQL 对象", _NUPS, "rule_dws_py"),
    _nups("nups.program.forbidden_table", "metadata", "报送程序不得引用禁用表清单中的表", "err",
          "检查程序文本是否包含 all_sstb 元数据返回的任一表名。",
          "引用已列入禁用清单的表可能读取过期或不再允许使用的数据。",
          "当 all_sstb 元数据读取成功且其表名（大小写不敏感）出现在源文本中时触发。",
          "NUPS Python 加工文件及其表引用", _NUPS, "rule_dws_py"),
    _nups("nups.program.scalar_subquery", "python", "报送程序中的标量子查询须确认单行结果", "err",
          "检查去除普通空格和 TAB 后的程序文本是否包含 =(SELECT。",
          "若等号右侧子查询返回多行，数据库会在执行时报告标量子查询错误。",
          "去除普通空格和 TAB 并转为大写后包含 =(SELECT 时触发；不解析子查询基数。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.in_subquery", "python", "报送程序中的 IN 子查询须核对扫描范围", "err",
          "检查去除普通空格和 TAB、并移除 JOIN(SELECT 后的程序文本是否包含 IN(SELECT。",
          "大型子查询可能读取较多数据并增加作业时间；文本命中不能证明实际扫描量。",
          "归一化文本包含 IN(SELECT 即触发，不分析执行计划或子查询大小。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.end_dt_range", "python", "拉链表查询须核对 END_DT 上界", "err",
          "检查归一化后的程序文本是否包含 .END_DT>=。",
          "结束日期边界可能与有效期筛选重叠，造成同一业务对象重复返回。",
          "去除普通空格和 TAB 并转为大写后出现 .END_DT>= 时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_to_date", "python", "主题表日期过滤不得对 D_DATE 使用 TO_DATE", "err",
          "检查主题表 SQL 是否使用 TO_DATE 转换 D_DATE。",
          "对分区日期字段套用转换函数可能使约定过滤或分区裁剪不生效。",
          "当 detect_d_date_issues 返回 d_date_to_date 时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_literal", "python", "主题表日期过滤不得使用 DATE 字面量", "err",
          "检查主题表 SQL 是否使用 DATE 字面量比较 D_DATE。",
          "不符合主题表日期约定的字面量可能绕开既定分区筛选方式。",
          "当 detect_d_date_issues 返回 d_date_literal 时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_function", "python", "主题表日期过滤不得转换 D_DATE", "err",
          "检查主题表 SQL 是否对 D_DATE 使用 DATE 函数。",
          "对日期分区列执行函数转换可能阻止过滤条件直接作用于分区列。",
          "当 detect_d_date_issues 返回 d_date_function 时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.to_date_d_date", "python", "主题表日期过滤不得转换 D_DATE", "err",
          "检查主题表 SQL 是否将 D_DATE 作为 TO_DATE 的输入。",
          "对日期分区列进行字符串转换可能使过滤表达式偏离主题表的日期约定。",
          "当 detect_d_date_issues 返回 to_date_d_date 时触发。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_less_than", "python", "主题表 D_DATE 范围须符合全量表约定", "err",
          "检查全量主题表 SQL 是否为 D_DATE 设置小于条件。",
          "对全量主题表使用日期下界可能排除所需历史记录。",
          "当 detect_d_date_issues 返回 d_date_less_than 时触发；不确认对象是否为全量表。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_greater_than", "python", "主题表 D_DATE 范围须符合全量表约定", "err",
          "检查全量主题表 SQL 是否为 D_DATE 设置大于条件。",
          "对全量主题表使用日期上界可能排除有效记录或批次数据。",
          "当 detect_d_date_issues 返回 d_date_greater_than 时触发；不确认对象是否为全量表。",
          "NUPS Python 加工文件及其中的 SQL", _NUPS, "rule_dws_py"),

    # FineReport menu and authority rules.
    _fine("fine.menu.root_prefix", "menu", "后台目录路径必须包含数据仓库根路径", "err",
          "检查后台目录路径是否包含规定的数据仓库根路径。",
          "目录路径未包含统一根路径时，导入后的报表可能无法映射到预期目录结构。",
          "读取 menu.txt 每个有效行后，后台路径 cpturl 不包含 required_root_prefix 时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu",
          ("fine_report.menu_normalization.required_root_prefix",)),
    _fine("fine.menu.backend_extension", "menu", "后台目录路径必须指向 CPT 或 FRM 模板", "err",
          "检查后台目录文本是否同时缺少 .cpt 和 .frm 子串。",
          "没有支持的模板扩展名时，路径可能无法对应可发布的 FineReport 模板。",
          "当 cpturl 中既不存在大小写敏感的 .cpt，也不存在 .frm 时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu"),
    _fine("fine.menu.backend_department_brackets", "menu", "后台目录部门名称须使用中文括号", "err",
          "检查后台目录是否包含半角括号包围的指定部门名称。",
          "同一部门名称使用不同括号形式会造成目录名称不一致并影响检索。",
          "当 cpturl 包含字面量 (村镇银行发展部) 时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu"),
    _fine("fine.menu.backend_department", "menu", "后台目录部门名须采用登记名称", "err",
          "检查后台目录是否仍使用需要调整的部门名称。",
          "旧部门名称会使报表继续归入已调整的目录分组。",
          "当 cpturl 包含 menu_normalization.replacements 中 locations 含 backend 的任一 source 时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu",
          ("fine_report.menu_normalization.replacements",)),
    _fine("fine.menu.backend_space", "menu", "后台目录路径不得包含空格", "err",
          "检查后台目录字段是否含 ASCII 空格。",
          "空格可能使目录解析、路径匹配或人工检索产生歧义。",
          "当 cpturl 中出现普通空格时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu"),
    _fine("fine.menu.frontend_root_prefix", "menu", "前台目录不得包含数据仓库根路径", "err",
          "检查前台目录路径是否含有仅应出现在后台路径中的数据仓库根路径。",
          "前台路径带入后台根路径时，导入目录可能多出一个层级并与预期结构不匹配。",
          "当 finememu 包含 required_root_prefix 时触发；代码检查子串而非仅检查开头。",
          "FineReport menu.txt 的前台目录字段", "rule_menu",
          ("fine_report.menu_normalization.required_root_prefix",)),
    _fine("fine.menu.frontend_department", "menu", "前台目录部门名须采用登记名称", "err",
          "检查前台目录是否仍使用需要调整的部门名称。",
          "旧部门名称会使报表继续归入已调整的目录分组。",
          "当 finememu 包含 menu_normalization.replacements 中 locations 含 menu 的任一 source 时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu",
          ("fine_report.menu_normalization.replacements",)),
    _fine("fine.menu.frontend_finance_department", "menu", "前台目录不得使用旧互联网金融部名称", "err",
          "检查前台目录是否仍使用“互联网金融部”这一旧部门名称。",
          "目录仍使用已调整的部门名称时，报表检索和目录权限可能继续依赖旧分类。",
          "当 menu 替换来源集合含“互联网金融部”且 finememu 也含该字符串时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu",
          ("fine_report.menu_normalization.replacements",)),
    _fine("fine.menu.frontend_department_brackets", "menu", "前台目录部门名称须使用半角括号", "err",
          "检查前台目录是否含全角括号包围的指定部门名称。",
          "括号形式不一致会形成重复或难以匹配的目录名称。",
          "当 finememu 包含字面量（村镇银行发展部）时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu"),
    _fine("fine.menu.frontend_extension", "menu", "前台目录不得包含 CPT 扩展名", "err",
          "检查前台目录字段是否包含大小写敏感的 .cpt 子串。",
          "前台目录字段应标识目录而非模板文件，文件名会造成路径层级混淆。",
          "当 finememu 中出现 .cpt 时触发；该规则不检查 .frm。",
          "FineReport menu.txt 的前台目录字段", "rule_menu"),
    _fine("fine.menu.frontend_space", "menu", "前台目录路径不得包含空格", "err",
          "检查前台目录字段是否含 ASCII 空格。",
          "空格可能使目录解析、路径匹配或人工检索产生歧义。",
          "当 finememu 中出现普通空格时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu"),
    _fine("fine.authority.missing_role", "permission", "报表授权角色必须存在于生产", "err",
          "检查 authority.txt 中列出的角色名称是否存在于生产角色元数据。",
          "未登记角色无法按预期授予报表访问权限，可能使用户失去所需访问或权限配置无法生效。",
          "当角色元数据可读取且某一权限项不在 all_role 返回集合中时触发。",
          "FineReport authority.txt 的角色字段", "rule_authority"),
    _fine("fine.authority.missing_menu", "permission", "已授权报表必须存在于报表目录", "err",
          "检查 authority.txt 中规范化后的报表名称是否存在于生产报表或本次 menu 列表。",
          "权限记录引用不存在的目录项时，授权对象无法对应到可访问的报表。",
          "当报表名非空且不在 all_fine 与 menu 名称的合并集合中时触发。",
          "FineReport authority.txt 的报表名称及目录元数据", "rule_authority"),

    # FineReport report/template rules.
    _fine("fine.report.missing_number", "report", "报表模板文件名必须包含编号标记", "err",
          "检查模板文件名是否同时包含左方括号和右方括号。",
          "没有约定编号标记时，报表难以与需求或目录中的编号对应。",
          "当文件名缺少 [ 或 ] 任一字符时触发；不校验括号内编号格式。",
          "FineReport CPT / FRM 模板文件名", "rule_fine"),
    _fine("fine.report.name_space", "report", "报表模板路径不得包含空格", "err",
          "检查传入模板路径是否包含 ASCII 空格。",
          "路径中的空格可能导致文件系统、发布工具或后续路径匹配出现差异。",
          "当 fine_name 任意位置出现普通空格时触发。",
          "FineReport CPT / FRM 模板路径", "rule_fine"),
    _fine("fine.report.distinct_review", "report", "报表 SQL 中的 DISTINCT 须核对去重范围", "warn",
          "检查 FineReport 模板文本是否包含 DISTINCT 字符串，不判断去重是否必要。",
          "不必要的去重可能增加查询开销；错误去重也可能掩盖关联产生的重复行。",
          "当模板全文大写化后包含 DISTINCT 时触发；并非只检查提取后的 SQL。",
          "FineReport CPT / FRM 模板及其中的 SQL", "rule_fine"),
    _fine("fine.report.group_only", "report", "报表模板不得仅配置分组展示模式", "warn",
          "检查模板文本是否包含精确 XML 片段 <ATTR DIVIDEMODE=\"1\"/>。",
          "模板若只有分组展示配置，用户可能看不到预期的明细行。",
          "当原始模板内容大小写敏感地包含该 XML 字面量时触发。",
          "FineReport CPT / FRM 模板 XML", "rule_fine"),
    _fine("fine.report.org_tree_default", "report", "权限机构树默认值须匹配当前用户机构", "err",
          "检查机构树报表的默认机构是否关联当前登录用户。",
          "默认机构不随登录用户变化时，报表可能展示错误机构范围或无法正确限定数据。",
          "当原始模板含“权限机构树”且 SQL 未匹配预设 ORG_TREE_DEFAULT_SQL_PATTERN 时触发；正则仅覆盖该文本形态。",
          "FineReport CPT / FRM 模板中的 SQL", "rule_fine"),
    _fine("fine.report.sensitive_fields", "report", "报表查询字段须按敏感级别核对", "warn",
          "检查报表数据集查询是否涉及需要分级管理的敏感字段。",
          "个人身份、联系方式或账户字段若未经适当授权展示，可能暴露不必要的个人或账户信息。",
          "当提取 SQL 命中错误级别关键词时当前输出 ERR；命中其他已配置或默认警告关键词时输出 WARN。",
          "FineReport CPT / FRM 模板提取出的数据集 SQL", "rule_fine",
          ("fine_report.sensitive_field_rules",)),
    _fine("fine.report.hardcoded_date", "report", "报表 SQL 不得依赖疑似硬编码日期", "warn",
          "检查报表查询中是否出现疑似固定日期。",
          "固定日期可能使报表长期查询错误期间；正则命中本身不能证明日期具有业务含义。",
          "find_hardcoded_dates 在提取 SQL 中返回一个或多个候选时触发；属于文本启发式。",
          "FineReport CPT / FRM 模板提取出的数据集 SQL", "rule_fine"),
    _fine("fine.report.scalar_subquery", "report", "报表 SQL 中的标量子查询须确认单行结果", "warn",
          "检查报表查询中是否包含标量子查询表达式。",
          "若等号右侧子查询返回多行，执行时会发生标量子查询错误。",
          "提取 SQL 大写化后包含 =(SELECT 即触发；不分析子查询基数。",
          "FineReport CPT / FRM 模板提取出的数据集 SQL", "rule_fine"),
    _fine("fine.report.in_subquery", "report", "报表 SQL 中的 IN 子查询须核对扫描范围", "warn",
          "检查报表查询中是否包含 IN 子查询。",
          "大型子查询可能读取较多数据并增加报表加载时间；文本命中不能证明实际扫描量。",
          "提取 SQL 大写化并移除 JOIN(SELECT 后，包含 IN(SELECT 即触发；不分析执行计划。",
          "FineReport CPT / FRM 模板提取出的数据集 SQL", "rule_fine"),
    _fine("fine.report.end_dt_range", "report", "报表拉链查询须核对 END_DT 上界", "err",
          "检查提取 SQL 是否包含 .END_DT>= 子串。",
          "结束日期边界可能与有效期条件重叠，导致报表重复展示历史版本。",
          "当提取 SQL 大写化后包含 .END_DT>= 时触发。",
          "FineReport CPT / FRM 模板提取出的数据集 SQL", "rule_fine"),
    _fine("fine.report.d_date_to_date", "report", "主题表日期过滤不得对 D_DATE 使用 TO_DATE", "err",
          "检查主题表日期条件是否对 D_DATE 使用 TO_DATE 转换。",
          "对分区日期列套用转换函数可能使约定的日期过滤或分区裁剪不生效。",
          "当原始模板内容大小写敏感地包含 D_DATE=TO_DATE(' 时触发。",
          "FineReport CPT / FRM 模板及其中的 SQL", "rule_fine"),
    _fine("fine.report.d_date_literal", "report", "主题表日期过滤不得使用 DATE 字面量", "err",
          "检查主题表日期条件是否使用 DATE 字面量比较 D_DATE。",
          "不符合主题表日期约定的字面量可能绕开既定分区筛选方式。",
          "当原始模板内容大小写敏感地包含 D_DATE=DATE' 时触发。",
          "FineReport CPT / FRM 模板及其中的 SQL", "rule_fine"),
    _fine("fine.report.missing_schema", "report", "报表 SQL 中的表引用必须带 schema", "warn",
          "检查报表查询引用的业务表是否明确标明所属 schema。",
          "未限定 schema 的引用可能依赖运行账户默认值，造成开发与生产解析到不同对象。",
          "提取表名和点分隔字符串后，排除内置名称，剩余名称不含点号即触发；CTE 或别名可能误命中。",
          "FineReport CPT / FRM 模板提取出的数据集 SQL", "rule_fine"),
)

RULES_BY_ID = MappingProxyType({rule.id: rule for rule in RULES})


def resolve_rule(rule_id: str) -> RuleDefinition | None:
    """Return static metadata for a registered business rule ID."""
    return RULES_BY_ID.get(rule_id)


def rule_inventory() -> tuple[dict[str, object], ...]:
    """Return a machine-readable inventory using the short ``severity`` key."""
    inventory = []
    for rule in RULES:
        entry = asdict(rule)
        entry["severity"] = entry.pop("default_severity")
        inventory.append(entry)
    return tuple(inventory)
