"""Static, typed metadata for business audit rules.

This registry describes existing checks only. It neither configures policies nor
executes a checker; policy values remain in audit_rules.yaml and behavior stays
in the workflow implementation.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from types import MappingProxyType
from typing import Literal


Workflow = Literal["hcyt", "nups", "fine-report"]
Category = Literal[
    "sql", "ddl", "python", "script", "schedule", "dependency",
    "metadata", "asset_registry", "config", "menu", "permission", "report",
]
Severity = Literal["err", "warn"]


@dataclass(frozen=True, slots=True)
class RuleImplementation:
    module: str
    function: str


@dataclass(frozen=True, slots=True)
class RuleDefinition:
    id: str
    workflow: Workflow
    category: Category
    title: str
    default_severity: Severity
    description: str
    rationale: str
    trigger_condition: str
    artifact: str
    config_keys: tuple[str, ...]
    implementation: tuple[RuleImplementation, ...]


def _rule(
    rule_id: str,
    workflow: Workflow,
    category: Category,
    title: str,
    severity: Severity,
    description: str,
    rationale: str,
    trigger: str,
    artifact: str,
    module: str,
    function: str,
    config: tuple[str, ...] = (),
    additional_implementations: tuple[RuleImplementation, ...] = (),
) -> RuleDefinition:
    return RuleDefinition(
        id=rule_id,
        workflow=workflow,
        category=category,
        title=title,
        default_severity=severity,
        description=description,
        rationale=rationale,
        trigger_condition=trigger,
        artifact=artifact,
        config_keys=config,
        implementation=(RuleImplementation(module, function), *additional_implementations),
    )


_HCYT_PY = "app.modules.audit.workflows.hcyt.checks.python_rule"
_HCYT_SQL = "app.modules.audit.workflows.hcyt.checks.sql_rule"
_HCYT_DDL = "app.modules.audit.workflows.hcyt.checks.ddl_rule"
_HCYT_SCHEDULE = "app.modules.audit.workflows.hcyt.checks.schedule_rule"
_HCYT_SENSITIVE_SQL = "app.modules.audit.workflows.hcyt.checks.sensitive_sql"
_NUPS = "app.modules.audit.workflows.nups.checks"
_FINE = "app.modules.audit.workflows.fine_report.checks"
_SHARED_DWS = "app.modules.audit.shared.dws_sql_review"


def _hcyt(
    rule_id: str, category: Category, title: str, severity: Severity,
    description: str, rationale: str, trigger: str, artifact: str,
    module: str, function: str, config: tuple[str, ...] = (),
    additional_implementations: tuple[RuleImplementation, ...] = (),
) -> RuleDefinition:
    return _rule(rule_id, "hcyt", category, title, severity, description, rationale,
                 trigger, artifact, module, function, config, additional_implementations)


def _nups(
    rule_id: str, category: Category, title: str, severity: Severity,
    description: str, rationale: str, trigger: str, artifact: str,
    module: str, function: str, config: tuple[str, ...] = (),
) -> RuleDefinition:
    return _rule(rule_id, "nups", category, title, severity, description, rationale,
                 trigger, artifact, module, function, config)


def _fine(
    rule_id: str, category: Category, title: str, severity: Severity,
    description: str, rationale: str, trigger: str, artifact: str,
    function: str, config: tuple[str, ...] = (),
) -> RuleDefinition:
    return _rule(rule_id, "fine-report", category, title, severity, description, rationale,
                 trigger, artifact, _FINE, function, config)


RULES: tuple[RuleDefinition, ...] = (
    # HCYT: configuration, DDL, file, SQL and program rules.
    _hcyt("hcyt.ddl.temp_table_name", "ddl", "临时表名须匹配配置前缀", "err",
          "检查提取出的临时表或 TMP schema 表名是否以当前配置的临时表前缀开头。",
          "临时对象未使用约定前缀，可能被误认为持久业务表或无法按临时表约定管理。",
          "CREATE TABLE 对象由原始 SQL 文本正则提取，ALTER TABLE 对象由正则提取；临时状态由对象 schema 或所在语句文本中的 TEMP 标记判断，名称未匹配任一配置前缀时触发。解析不排除注释或字符串。",
          "DWS SQL 中正则提取的表对象", _HCYT_DDL, "check_table_name_rule",
          ("dws.naming.temporary_table_prefixes",)),
    _hcyt("hcyt.ddl.table_name", "ddl", "分层表名须匹配 schema 配置前缀", "err",
          "检查正则提取出的 DDL 表名及加工程序路径解析出的结果表名是否以所属 schema 的配置前缀开头。",
          "分层表名前缀不匹配会使对象难以按数据层识别，并可能造成依赖方误用。",
          "CREATE/ALTER TABLE 候选由原始 SQL 文本正则提取；另检查加工程序父目录名解析出的结果表。仅对配置了前缀的 schema 判断；SQL 文本提取不排除注释或字符串。",
          "DWS SQL 中正则提取的表对象或加工程序路径结果表", _HCYT_DDL, "check_table_name_rule",
          ("dws.naming.schema_prefixes",)),
    _hcyt("hcyt.ddl.column_comment", "ddl", "指定 schema 的字段须提供可识别注释", "err",
          "检查正则提取出的 CREATE TABLE 字段和 ALTER TABLE ADD COLUMN 字段是否含行内 COMMENT 或匹配的 COMMENT ON COLUMN。",
          "未提取到字段注释时，下游使用者难以从表结构确认字段含义；规则不评价注释内容质量。",
          "仅对 comment_required_schemas 中的表检查；字段定义、ALTER ADD COLUMN 和 COMMENT ON COLUMN 均通过文本正则/分隔逻辑提取，未提取到任一种非空注释时触发。原始文本中的注释或字符串可能影响匹配。",
          "DWS SQL 中可提取的字段定义与 COMMENT 语句", _HCYT_DDL, "check_column_comment_rule",
          ("dws.naming.comment_required_schemas",)),
    _hcyt("hcyt.ddl.table_root", "ddl", "指定 schema 的表名词根须匹配登记词根", "err",
          "检查可提取表名去除配置前缀后按下划线分割的词段是否都存在于资产词根元数据。",
          "未登记词段可能无法按现有资产词汇检索和解释；检测只按词段精确比对，不判断业务同义词。",
          "仅当词根元数据可读取、表名由 CREATE TABLE 正则提取且 schema 在 root_check_required_schemas 中时，对去除配置前缀并按下划线拆分的非数字词段逐个查找；任一未登记即触发。SQL 文本不排除注释或字符串。",
          "DWS SQL 中正则提取的 CREATE TABLE 名称与词根元数据", _HCYT_DDL, "check_table_root_rule",
          ("dws.naming.root_check_required_schemas", "dws.naming.schema_prefixes",
           "dws.naming.temporary_table_prefixes")),
    _hcyt("hcyt.ddl.column_root", "ddl", "指定 schema 的字段名词根须匹配登记词根", "err",
          "检查可提取字段名按下划线分割后的词段是否都存在于资产词根元数据。",
          "未登记词段可能无法按统一词汇检索和解释；检测只按词段精确比对，不判断业务同义词。",
          "仅当词根元数据可读取、字段由 CREATE TABLE 或 ALTER TABLE ADD COLUMN 正则/分隔逻辑提取且 schema 在 root_check_required_schemas 中时，对非数字词段逐个查找；任一未登记即触发。SQL 文本不排除注释或字符串。",
          "DWS SQL 中可提取的字段名与词根元数据", _HCYT_DDL, "check_column_root_rule",
          ("dws.naming.root_check_required_schemas",)),
    _hcyt("hcyt.dwf.empty_code_mapping", "metadata", "DWF 文本命中空码值赋值模式须复核", "err",
          "在 DWF 文件全文中搜索 SRC_TBL_ENG_NM = '' 或 SRC_CD_FLD_ENG_NM = '' 字符串，不解析赋值语句。",
          "若命中内容属于实际码值映射配置，来源表或来源码值字段为空时映射关系可能无法确定；文本命中本身不证明配置生效。",
          "读取 DWF 文件后以大小写不敏感方式搜索任一指定完整子串；不剔除注释或字符串，也不允许等号附近空白变化。",
          "DWF 加工文件全文", _HCYT_PY, "rule_dwf"),
    _hcyt("hcyt.dwo.legacy_version", "python", "DWO 文本命中旧模板标记组合须复核", "err",
          "检查 DWO 文件全文是否同时包含旧版本标记和湖仓联通算法描述的指定字符串。",
          "若两段文本对应实际旧版模板，该模板可能不符合当前作业所需字段或处理约定；子串匹配不证明模板版本或用途。",
          "当整个文件大小写不敏感地包含“版 本 号: v 1.0”和“功能描述: 湖仓联通加工算法”两段文本时触发；不解析模板结构，注释和字符串也可能命中。",
          "DWO 加工文件全文", _HCYT_PY, "rule_dwo"),
    _hcyt("hcyt.recv.custom_export", "config", "卸数配置文本命中自定义模式须复核", "err",
          "按路径中的指定子串及文件全文中的精确文本片段判断是否命中该复核条件，不解析 JSON 字段或 schema。",
          "若该文件确属自定义卸数配置且环境信息不正确，作业可能读取错误环境的数据；当前模式只能提示复核。",
          "当路径大小写敏感地不含 003.DLK_DLO.、010.DWS_DWF.、LOCAL_，且文件全文转为大写后不含精确片段 \"SQL\" : \"\" 时触发；不解析 JSON，也不规范化空白。",
          "recv JSON 配置文件路径与全文", _HCYT_PY, "rule_recv_json"),
    _hcyt("hcyt.sbin.tab_character", "script", "后置 Python 脚本不得包含 TAB", "err",
          "检查扩展名为 .py 的后置脚本内容是否包含制表符字符。",
          "TAB 与空格混用可能造成 Python 缩进错误，也会使脚本显示和编辑结果不一致。",
          "当被分类为后置脚本的 .py 文件中出现任意 TAB 字符时触发；字符串和注释中的 TAB 也会命中。",
          "后置 Python 脚本", _HCYT_PY, "rule_sbin"),
    _hcyt("hcyt.sbin.dos_format", "script", "后置脚本首行检测到 DOS 换行须复核", "err",
          "检查后置脚本首行是否包含 DOS 的 CRLF 换行符。",
          "首行换行格式与目标环境不一致时，脚本解释或部署过程可能出现差异；该检查不验证文件其余行。",
          "detect_file_format 只读取文件首行；首行含 CRLF 时触发，LF 时不触发，无换行符时返回 Unknown。",
          "后置脚本文件首行", _HCYT_PY, "rule_sbin"),

    # HCYT program source rules. Text-pattern findings are intentionally described as heuristics.
    _hcyt("hcyt.program.create_view", "python", "加工程序文本中的 CREATE VIEW 模式须复核", "err",
          "在加工程序全文中用正则搜索 CREATE [OR REPLACE] VIEW 后接对象名的文本模式。",
          "若命中内容是实际视图定义，新增或改变共享数据库对象可能影响其他作业；文本命中本身不证明存在有效定义。",
          "对整个程序源文本大写化后匹配 CREATE [OR REPLACE] VIEW <简单或 schema 限定名称>；不剔除注释和字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.create_function", "python", "加工程序文本中的 CREATE FUNCTION 模式须复核", "err",
          "在加工程序全文中用正则搜索 CREATE [OR REPLACE] FUNCTION 后接对象名的文本模式。",
          "若命中内容是实际函数定义，新增共享数据库对象可能影响调用方；文本命中本身不证明存在有效定义。",
          "对整个程序源文本大写化后匹配 CREATE [OR REPLACE] FUNCTION <简单或 schema 限定名称>；不剔除注释和字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.recursive_query", "python", "加工程序文本中的 RECURSIVE 标记须复核", "err",
          "检查加工程序源文本是否包含 RECURSIVE 子串，不解析递归查询结构。",
          "若该标记属于实际递归查询，递归范围或终止条件不当可能增加执行时间和资源消耗；注释或字符串命中不代表查询行为。",
          "读取整个程序源文本并转为大写后搜索 RECURSIVE；注释和字符串也会命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.for_loop", "python", "加工程序文本中的 FOR I IN 模式须复核", "err",
          "在加工程序源文本中搜索连续文本 FOR I IN。",
          "若命中内容是实际循环且循环体重复执行查询或写入，可能延长作业时间；文本模式本身不证明其为 Python 循环。",
          "读取整个程序源文本并转为大写后搜索 FOR I IN；不解析 Python 语法，注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.character_varying_length", "python", "加工程序文本中的 CHARACTER VARYING( 模式须复核", "err",
          "检查加工程序源文本是否包含 CHARACTER VARYING( 字符串，不解析字段声明。",
          "若该模式属于实际定长字段声明，字段长度可能无法容纳较长值；命中本身不能证明发生截断或写入失败。",
          "读取整个程序源文本并转为大写后搜索 CHARACTER VARYING(；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.varchar2_length", "python", "加工程序文本中的 VARCHAR2( 模式须复核", "err",
          "检查加工程序源文本是否包含 VARCHAR2( 字符串，不解析字段声明。",
          "若该模式属于实际定长字段声明，字段长度可能无法容纳较长值；命中本身不能证明发生截断或写入失败。",
          "读取整个程序源文本并转为大写后搜索 VARCHAR2(；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.nested_nvl", "python", "加工程序文本中的 NVL(NVL( 模式须复核", "err",
          "检查加工程序源文本是否包含 NVL(NVL( 字符串，不解析函数调用结构。",
          "若命中内容是实际嵌套空值处理，取值回退路径可能较难核对；文本匹配本身不证明存在嵌套函数调用。",
          "读取整个程序源文本并转为大写后搜索 NVL(NVL(；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.nested_coalesce", "python", "加工程序文本中的 COALESCE(COALESCE( 模式须复核", "err",
          "检查加工程序源文本是否包含 COALESCE(COALESCE( 字符串，不解析函数调用结构。",
          "若命中内容是实际嵌套空值处理，取值优先级可能较难核对；文本匹配本身不证明存在嵌套函数调用。",
          "读取整个程序源文本并转为大写后搜索 COALESCE(COALESCE(；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.distinct_review", "python", "加工程序文本命中 DISTINCT 须核对去重范围", "warn",
          "检查加工程序源文本是否包含 DISTINCT 字符串，不解析查询语句。",
          "若 DISTINCT 位于实际查询中，不必要的去重可能增加排序或哈希开销；不恰当的去重也可能掩盖关联产生的重复行。",
          "读取整个程序源文本并转为大写后搜索 DISTINCT；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.legacy_outer_join", "python", "加工程序文本中的 (+) 模式须复核", "err",
          "检查加工程序源文本是否包含 (+) 字符串，不解析外连接语法。",
          "若命中内容属于旧式外连接，条件分布不直观，修改过滤条件时可能改变保留行语义；注释或字符串命中不代表查询使用该写法。",
          "读取整个程序源文本并转为大写后搜索 (+)；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.affected_rows_log", "python", "加工程序文本须包含影响条数标记", "err",
          "检查加工程序源文本是否包含“影响条数”字符串，不验证日志调用。",
          "缺少该文本标记时，审核人员较难从源文件中定位影响行数日志；标记存在也不证明日志会执行或数量准确。",
          "当整个程序源文本不含“影响条数”时触发；不检查字符串是否位于可执行日志语句中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.legacy_group_clause", "python", "加工程序文本中的 TO GROUP GROUP_VERSION1 模式须复核", "err",
          "检查加工程序源文本是否包含 TO GROUP GROUP_VERSION1 字符串，不解析 SQL 子句。",
          "若命中内容是实际旧版 GROUP 子句，可能与当前数据库部署约定不兼容；文本命中不能证明该语句会执行。",
          "读取整个程序源文本并转为大写后搜索 TO GROUP GROUP_VERSION1；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.hardcoded_date", "python", "加工程序文本中的日期候选须复核", "err",
          "在加工程序源文本第 1001 个字符起搜索带引号的 YYYYMMDD 或 YYYY-MM-DD 日期候选，并仅保留可解析且年份在 1900–3000 的值。",
          "若候选是实际查询中的固定日期，可能使后续批次处理旧期间或遗漏新期间；正则命中不证明日期用途。",
          "对 data[1000:] 调用 find_hardcoded_dates；扫描源文件尾段而非提取 SQL，匹配可出现在注释或字符串中。",
          "DWS 加工 Python 源文件第 1001 字符起", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.use_view", "python", "程序文本候选名称命中已登记视图须复核", "err",
          "在程序文本提取的对象名称候选中查找与视图元数据匹配的名称，不解析 SQL 对象引用。",
          "若命中项确为视图引用，视图定义或底层数据变化可能改变作业结果；候选匹配本身不能证明实际依赖。",
          "仅当视图元数据可读取时检查 data[1000:] 经 extract_tables 与 find_dot_strings 提取的候选；排除内置名后与登记视图名匹配即触发，结果表在此匹配后才被过滤，注释和字符串也可能命中。",
          "DWS 加工 Python 源文件第 1001 字符起及视图元数据", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.use_function", "python", "程序文本命中已登记函数调用模式须复核", "err",
          "用正则在加工程序源文本中搜索登记函数名后跟左括号的模式，不解析 SQL 或 Python 调用。",
          "若命中项确为数据库函数调用，函数实现变化可能改变结果或运行成本；文本模式不能证明调用会执行。",
          "仅当函数元数据可读取时，对整个源文本按大小写不敏感的函数名\\s*\\(模式匹配；注释和字符串也可能命中。",
          "DWS 加工 Python 源文件全文及函数元数据", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.partition_rollback", "python", "结果表分区状态须与回滚步骤文本核对", "err",
          "比较结果表的分区数是否大于 0，与源文本是否同时匹配 rollback_deal 定义和分区操作模式。",
          "分区表缺少对应回滚步骤可能留下不完整结果；非分区表却包含该步骤也可能执行不符预期。",
          "仅当结果表分区元数据可读取且首个计数值非空时比较：分区数大于 0 的布尔值与全文同时命中 DEF ROLLBACK_DEAL( 及 TRUNCATE/ADD/DROP/SPLIT PARTITION 的布尔值不同时触发；注释和字符串也可命中。",
          "DWS 加工 Python 源文件及结果表分区元数据", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.missing_schema", "python", "加工程序中的未限定名称候选须复核", "err",
          "检查从程序源文本提取、且未被排除为内置名、结果表或已登记函数的名称候选是否含点号。",
          "若命中项确为未限定表引用，默认 schema 可能使不同运行账户解析到不同对象；候选误报需先确认其 SQL 角色。",
          "仅处理 data[1000:]：extract_tables 与 find_dot_strings 从文本提取候选，过滤后不含点号即触发；不做 SQL 解析，CTE、注释或字符串可误命中。",
          "DWS 加工 Python 源文件第 1001 字符起及候选对象名", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.forbidden_table", "python", "加工程序文本命中禁用表名须复核", "err",
          "检查禁用表元数据中的名称是否以大小写不敏感方式出现在加工程序源文本中，不解析 SQL 表引用。",
          "若命中名称属于实际来源引用，可能使用已列入禁用清单的数据；文本命中也可能来自注释或字符串。",
          "当禁用表元数据读取成功且任一表名（忽略大小写）是整个源文本的子串时触发；不区分代码、注释、字符串或 SQL 语句。",
          "DWS 加工 Python 源文件全文及禁用表元数据", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.scalar_subquery", "python", "加工程序文本中的 =(SELECT 模式须复核", "err",
          "检查去除普通空格和 TAB 后的整个程序源文本是否包含 =(SELECT 字符串。",
          "若该文本属于等号右侧标量子查询且结果多于一行，执行可能失败；检测器不判断语法或查询基数。",
          "对整个源文本移除普通空格和 TAB 并转为大写后搜索 =(SELECT；不移除换行，也不排除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.in_subquery", "python", "加工程序文本中的 IN(SELECT 模式须复核", "warn",
          "检查去除普通空格和 TAB、移除 JOIN(SELECT 后的整个程序源文本是否包含 IN(SELECT 字符串。",
          "若命中内容属于大型实际子查询，可能扩大扫描范围或增加执行时间；文本匹配不证明查询规模或计划成本。",
          "对整个源文本移除普通空格和 TAB 并转为大写，再删除 JOIN(SELECT 子串；剩余文本包含 IN(SELECT 即触发，不排除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.end_dt_range", "python", "加工程序文本中的 .END_DT>= 模式须复核", "err",
          "检查去除普通空格和 TAB 后的程序源文本是否包含 .END_DT>= 字符串。",
          "若该模式是拉链表的有效期条件，边界写法可能影响有效记录筛选；命中本身不确认字段来源或比较语义。",
          "对整个程序源文本移除普通空格和 TAB 并转为大写后搜索 .END_DT>=；不解析 SQL，也不排除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_to_date", "python", "D_DATE=TO_DATE(' 文本模式须复核", "err",
          "在加工程序源文本中搜索 D_DATE 标识符后跟 TO_DATE(' 的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，对日期列套用转换可能影响过滤或分区裁剪；命中本身不能证明这一语义。",
          "对整个加工程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界、等号、TO_DATE( 和单引号之间允许空白；不剔除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_literal", "python", "D_DATE=DATE' 文本模式须复核", "err",
          "在加工程序源文本中搜索 D_DATE 标识符后跟 DATE 字面量的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，字面量形式可能不符合项目日期约定；命中本身不能证明对象或过滤意图。",
          "对整个加工程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界、等号及 DATE' 之间允许空白；不剔除注释或字符串，也不推断日期覆盖范围。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_function", "python", "DATE(D_DATE) 文本模式须复核", "err",
          "在加工程序源文本中搜索 DATE 函数参数包含 D_DATE 标识符的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，对日期列应用函数可能影响过滤或分区裁剪；命中本身不能证明这一语义。",
          "对整个加工程序源文本执行大小写不敏感正则匹配：DATE( 可含空白，参数允许可选 schema 限定的 D_DATE 标识符；不剔除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.to_date_d_date", "python", "TO_DATE(D_DATE, 文本模式须复核", "err",
          "在加工程序源文本中搜索 TO_DATE 参数以 D_DATE 标识符开头的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，字符串转换可能影响过滤或分区裁剪；命中本身不能证明这一语义。",
          "对整个加工程序源文本执行大小写不敏感正则匹配：TO_DATE( 可含空白，参数允许可选 schema 限定的 D_DATE 标识符并随后出现逗号；不剔除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_less_than", "python", "D_DATE 小于比较文本须复核", "err",
          "在加工程序源文本中搜索 D_DATE 标识符后跟小于号的模式；不判断对象是否为主题表或比较是否属于有效 SQL。",
          "若命中内容实际是全量数据的日期过滤条件，边界可能排除所需记录；检测器无法确认表类型或业务日期约定。",
          "对整个加工程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界后允许空白再跟 <；也会匹配 <=，且不剔除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),
    _hcyt("hcyt.program.d_date_greater_than", "python", "D_DATE 大于比较文本须复核", "err",
          "在加工程序源文本中搜索 D_DATE 标识符后跟大于号的模式；不判断对象是否为主题表或比较是否属于有效 SQL。",
          "若命中内容实际是全量数据的日期过滤条件，边界可能排除有效记录；检测器无法确认表类型或业务日期约定。",
          "对整个加工程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界后允许空白再跟 >；也会匹配 >=，且不剔除注释或字符串。",
          "DWS 加工 Python 源文件全文", _HCYT_PY, "rule_dws_py"),

    # HCYT SQL rules and the two active structured asset-issue identities.
    _hcyt("hcyt.sql.create_view", "sql", "DWS SQL 文本中的 CREATE VIEW 模式须复核", "err",
          "在 DWS SQL 全文中用正则搜索 CREATE [OR REPLACE] VIEW 后接对象名的文本模式。",
          "若命中内容是实际视图定义，定义变化可能改变其他作业读取的数据集；文本匹配不证明语句有效。",
          "对整个 SQL 文本大写化后匹配 CREATE [OR REPLACE] VIEW <简单或 schema 限定名称>；不剔除注释和字符串。",
          "DWS SQL 文件全文", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.create_function", "sql", "DWS SQL 文本中的 CREATE FUNCTION 模式须复核", "err",
          "在 DWS SQL 全文中用正则搜索 CREATE [OR REPLACE] FUNCTION 后接对象名的文本模式。",
          "若命中内容是实际函数定义，函数变化可能影响调用方结果或依赖；文本匹配不证明语句有效。",
          "对整个 SQL 文本大写化后匹配 CREATE [OR REPLACE] FUNCTION <简单或 schema 限定名称>；不剔除注释和字符串。",
          "DWS SQL 文件全文", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.use_view", "sql", "DWS SQL 文本候选名称命中登记视图须复核", "err",
          "从 DWS SQL 文本提取点分隔名称候选，并与已登记视图名称匹配；不解析 SQL 对象依赖。",
          "若命中项确为视图引用，视图定义或来源变化可能改变查询结果；文本候选匹配本身不证明实际依赖。",
          "仅当视图元数据可读取时，对 find_dot_strings(data.upper()) 返回的候选与登记视图名比较；候选仅保留指定 DWS schema 前缀（DM、DWA、DWD、DWUPRR、DWM、DWP、DWO、DWF），原文注释和字符串也可能命中。",
          "DWS SQL 全文及视图元数据", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.use_function", "sql", "DWS SQL 文本命中登记函数调用模式须复核", "err",
          "用正则在 DWS SQL 全文中搜索登记函数名后跟左括号的模式，不解析 SQL 调用。",
          "若命中项确为数据库函数调用，函数实现变化可能改变结果或运行成本；文本匹配不能证明调用会执行。",
          "仅当函数元数据可读取时，按大小写不敏感的函数名\\s*\\(模式扫描 SQL 全文；注释和字符串也可能命中。",
          "DWS SQL 全文及函数元数据", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.too_many_lines", "sql", "DWS SQL 文件不得超过 20,000 行", "err",
          "检查按换行符拆分后的 DWS SQL 行数是否大于 20,000。",
          "单文件体量过大时，人工定位变更和审查 SQL 语句的成本明显增加。",
          "当 len(data.split('\\n')) > 20000 时触发；空行也计入行数。",
          "DWS SQL 文件", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.dwm_operation", "sql", "DWS SQL 文本中的 DWM. 标记须复核", "warn",
          "检查 DWS SQL 全文是否包含 DWM. 子串，不区分读写操作。",
          "若命中内容对应模型层对象操作或引用，可能影响已发布模型和下游报表；该子串不证明实际对象或操作。",
          "当 SQL 全文（包括注释和字符串）大小写不敏感地包含 DWM. 时触发。",
          "DWS SQL 文件全文", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.legacy_group_clause", "sql", "DWS SQL 文本中的 TO GROUP GROUP_VERSION1 须复核", "err",
          "检查 DWS SQL 全文是否包含 TO GROUP GROUP_VERSION1 字符串，不解析 GROUP 子句。",
          "若命中内容是实际旧版 GROUP 语句，可能与当前数据库部署规则不兼容；注释或字符串命中不代表语句会执行。",
          "当 SQL 全文转为大写后包含 TO GROUP GROUP_VERSION1 时触发；不排除注释和字符串。",
          "DWS SQL 文件全文", _HCYT_SQL, "rule_dws"),
    _hcyt("hcyt.sql.manual_code_table_write", "asset_registry", "码值表写操作须与登记信息核对", "warn",
          "检查解析出的写操作目标是否出现在资产平台手工码值表登记中。",
          "直接写入受登记管理的码值表可能绕过其变更维护流程，导致码值定义与登记状态不一致。",
          "仅当码值表元数据可读取，且解析到的 INSERT、UPDATE、DELETE、MERGE、TRUNCATE 或相关 DDL 目标表代码存在于登记中时触发。",
          "DWS SQL 写操作及码值表登记元数据", _HCYT_SQL, "collect_manual_code_table_write_findings"),
    _hcyt("hcyt.sql.legacy_marker", "sql", "DWS SQL 文本命中已配置遗留标记须复核", "err",
          "检查 DWS SQL 全文是否包含配置的遗留标记字符串，并按配置排除项过滤。",
          "若命中内容对应实际旧取数引用，可能继续读取过期来源；字符串命中本身不能证明其用途。",
          "将 SQL 全文转为大写后，命中任一非空配置 marker 且未命中其 excludes 时触发；不排除注释和字符串。",
          "DWS SQL 文件全文", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.legacy_markers",)),
    _hcyt("hcyt.sql.protected_code_table", "asset_registry", "DWS SQL 文本命中受保护码值表名称须复核", "err",
          "检查 DWS SQL 全文是否包含任一配置的受保护码值表名称，不解析表引用或读写操作。",
          "若命中内容对应对受保护码值表的实际写入，可能改变共享码值映射；单纯文本命中不能证明发生修改。",
          "将 SQL 全文转为大写后搜索配置表名子串；不区分读写，也不排除注释和字符串。",
          "DWS SQL 全文及受保护码值表配置", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.protected_code_tables",)),
    _hcyt("hcyt.hive.too_many_lines", "sql", "Hive SQL 文件不得超过 20,000 行", "err",
          "检查按换行符拆分后的 Hive SQL 行数是否大于 20,000。",
          "单文件体量过大时，变更审查和问题定位需要在大量文本中搜索。",
          "当 len(data.split('\\n')) > 20000 时触发；空行也计入行数。",
          "Hive SQL 文件", _HCYT_SQL, "rule_hive"),
    _hcyt("hcyt.hive.varchar2_type", "sql", "Hive SQL 文本中的 VARCHAR2 字样须复核", "err",
          "检查 Hive SQL 全文是否包含 VARCHAR2 子串，不解析字段类型。",
          "若该文本属于实际字段类型声明，Hive 执行环境可能无法识别或产生类型不兼容；注释或字符串命中不代表使用了该类型。",
          "当 Hive SQL 全文转为大写后包含 VARCHAR2 时触发；注释和字符串也会命中。",
          "Hive SQL 文件全文", _HCYT_SQL, "rule_hive"),
    _hcyt("hcyt.sql.permission_change", "sql", "DWS SQL 中的权限变更须重点复核", "err",
          "检查顶层 SQL 语句是否为 GRANT 或 REVOKE。",
          "权限变更会改变主体对数据或对象的访问范围，错误授权可能暴露数据或阻断作业。",
          "仅当顶层语句命令为 GRANT 或 REVOKE 时触发；注释和字符串会在分词阶段跳过。",
          "DWS SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.identity_change", "sql", "DWS SQL 中的用户或角色变更须重点复核", "err",
          "检查顶层语句是否创建、修改或删除 ROLE / USER。",
          "身份对象变更会改变数据库主体和后续授权的适用范围。",
          "当顶层命令为 CREATE、ALTER 或 DROP，且后续对象类型为 ROLE 或 USER 时触发。",
          "DWS SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.destructive_ddl", "sql", "DWS SQL 中的对象删除须重点复核", "err",
          "检查顶层语句是否删除数据库对象、截断表，或删除表字段/分区。",
          "删除对象、数据或分区可能造成不可逆的数据缺失及下游作业失败。",
          "当解析到 DROP 支持对象、TRUNCATE，或 ALTER TABLE DROP COLUMN / PARTITION 时触发。",
          "DWS SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.unbounded_dml", "sql", "DWS SQL 的 UPDATE / DELETE 须包含 WHERE", "err",
          "检查顶层 UPDATE 或 DELETE 语句是否没有 WHERE token。",
          "无条件修改可能影响目标表全部记录，而非本次预期的数据范围。",
          "当顶层命令为 UPDATE 或 DELETE 且分词后不存在 WHERE 时触发；不计算过滤条件实际选择范围。",
          "DWS SQL 顶层 DML", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.overwrite_write", "sql", "DWS SQL 的覆盖写入须核对目标范围", "warn",
          "检查顶层 INSERT OVERWRITE 或包含 OVERWRITE 的 LOAD 语句。",
          "覆盖写入可能替换目标表或分区中已有数据，范围设置错误会丢失历史结果。",
          "当顶层命令为 INSERT 且第二个 token 是 OVERWRITE，或 LOAD 语句含 OVERWRITE 时触发。",
          "DWS SQL 顶层写入语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.sql.alter_statement", "sql", "DWS SQL 中的 ALTER 语句须重点复核", "warn",
          "检查无法归入身份变更、破坏性操作的顶层 ALTER 语句。",
          "ALTER 会改变数据库对象结构或属性，未经核对可能造成兼容性问题。",
          "当顶层命令为 ALTER 且未先命中身份变更、ALTER TABLE DROP 破坏性分支时触发。",
          "DWS SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.permission_change", "sql", "Hive SQL 中的权限变更须重点复核", "err",
          "检查顶层 Hive SQL 语句是否为 GRANT 或 REVOKE。",
          "权限变更会改变主体对数据或对象的访问范围，错误授权可能暴露数据或阻断作业。",
          "仅当顶层语句命令为 GRANT 或 REVOKE 时触发。",
          "Hive SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.identity_change", "sql", "Hive SQL 中的用户或角色变更须重点复核", "err",
          "检查顶层语句是否创建、修改或删除 ROLE / USER。",
          "身份对象变更会改变数据库主体和后续授权的适用范围。",
          "当顶层命令为 CREATE、ALTER 或 DROP，且对象类型为 ROLE 或 USER 时触发。",
          "Hive SQL 顶层语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.destructive_ddl", "sql", "Hive SQL 中的对象删除须重点复核", "err",
          "检查顶层语句是否删除支持的数据库对象、截断表，或删除表字段/分区。",
          "删除对象、数据或分区可能造成数据缺失及依赖作业失败。",
          "当解析到 DROP 支持对象、TRUNCATE，或 ALTER TABLE DROP COLUMN / PARTITION 时触发。",
          "Hive SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.unbounded_dml", "sql", "Hive SQL 的 UPDATE / DELETE 须包含 WHERE", "err",
          "检查顶层 UPDATE 或 DELETE 语句是否没有 WHERE token。",
          "无条件修改可能影响目标表全部记录，而非本次预期的数据范围。",
          "当顶层命令为 UPDATE 或 DELETE 且分词后不存在 WHERE 时触发。",
          "Hive SQL 顶层 DML", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.overwrite_write", "sql", "Hive SQL 的覆盖写入须核对目标范围", "warn",
          "检查顶层 INSERT OVERWRITE 或包含 OVERWRITE 的 LOAD 语句。",
          "覆盖写入可能替换目标表或分区已有数据，范围设置错误会丢失历史结果。",
          "当顶层命令为 INSERT 且第二个 token 是 OVERWRITE，或 LOAD 语句含 OVERWRITE 时触发。",
          "Hive SQL 顶层写入语句", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("hcyt.hive.alter_statement", "sql", "Hive SQL 中的 ALTER 语句须重点复核", "warn",
          "检查未被更具体身份变更或破坏性规则命中的顶层 ALTER 语句。",
          "ALTER 会改变数据库对象结构或属性，未经核对可能造成兼容性问题。",
          "当顶层命令为 ALTER 且未命中身份变更或 ALTER TABLE DROP 破坏性分支时触发。",
          "Hive SQL 顶层 DDL", _HCYT_SENSITIVE_SQL, "_scan_statement"),
    _hcyt("ASSET_TABLE_REVIEW", "asset_registry", "配置范围内的建表对象须纳入资产登记核对", "warn",
          "检查正则提取的 CREATE TABLE 对象或加工程序路径解析出的结果表 schema 是否在 asset_review_required_schemas 中。",
          "未登记的结果表可能无法被资产目录检索或被下游交付关系识别。",
          "SQL 文件中由正则从原始文本提取 CREATE TABLE 候选；schema 命中配置时生成资产问题。Python 加工文件另从父目录名解析结果表并按同一 schema 配置判断。SQL 提取不排除注释或字符串；该 ID 保持现有无 workflow 前缀形式。",
          "DWS SQL 中正则提取的建表对象或加工程序路径结果表", _HCYT_SQL, "collect_created_table_review_issues",
          ("dws.naming.asset_review_required_schemas",),
          (RuleImplementation(_HCYT_PY, "build_asset_table_review_issues"),
           RuleImplementation(_HCYT_DDL, "is_asset_review_required_table"))),
    _hcyt("ROOT_MISSING", "asset_registry", "表和字段名称词根须登记", "warn",
          "检查正则/分隔逻辑提取的表名和字段名词段是否已在资产词根库登记。",
          "未登记的词段可能无法按统一词汇检索和解释，降低资产名称的可发现性。",
          "仅当 all_term_roots 可读取且 schema 在 root_check_required_schemas 中时，对 CREATE TABLE 与 ALTER TABLE ADD COLUMN 提取的每个非数字缺失词段生成资产问题；提取不排除注释或字符串。若词根元数据查询异常，该 issue collector 捕获异常并返回空列表，不生成业务问题或专用诊断；该 ID 保持现有无 workflow 前缀形式。",
          "DWS SQL 中可提取的表名/字段名及词根元数据", _HCYT_DDL, "collect_root_missing_issues",
          ("dws.naming.root_check_required_schemas", "dws.naming.schema_prefixes",
           "dws.naming.temporary_table_prefixes")),

    # HCYT schedule inventory; generated IDs enumerate the current DWD/DWP/DWM config keys.
    _hcyt("hcyt.schedule.plan.invalid_name", "schedule", "计划名不得使用已禁用名称", "err",
          "检查上线计划名是否精确匹配 invalid_plan_names 中的值。",
          "沿用已禁用计划名可能覆盖或混淆现有生产调度对象。",
          "当计划表中非空计划名与配置禁用名称完全相等时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.invalid_plan_names",)),
    _hcyt("hcyt.schedule.plan.dwd_name", "schedule", "DWD 计划名必须匹配允许名称", "err",
          "检查名称含 DWD 关键字的计划是否属于配置的 DWD 允许名称。",
          "同层计划命名不一致会使运行人员难以判断计划用途，并可能造成调度对象重复。",
          "当计划名包含 DWD 且不在 plan_name_rules.DWD 列表中时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.plan_name_rules.DWD",)),
    _hcyt("hcyt.schedule.plan.dwp_name", "schedule", "DWP 计划名必须匹配允许名称", "err",
          "检查名称含 DWP 关键字的计划是否属于配置的 DWP 允许名称。",
          "同层计划命名不一致会使运行人员难以判断计划用途，并可能造成调度对象重复。",
          "当计划名包含 DWP 且不在 plan_name_rules.DWP 列表中时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.plan_name_rules.DWP",)),
    _hcyt("hcyt.schedule.plan.dwm_name", "schedule", "DWM 计划名必须匹配允许名称", "err",
          "检查名称含 DWM 关键字的计划是否属于配置的 DWM 允许名称。",
          "同层计划命名不一致会使运行人员难以判断计划用途，并可能造成调度对象重复。",
          "当计划名包含 DWM 且不在 plan_name_rules.DWM 列表中时触发。",
          "HCYT PLAN 调度表", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.plan_name_rules.DWM",)),
    _hcyt("hcyt.schedule.plan.predecessor", "dependency", "计划不得登记未核对的前置计划", "warn",
          "检查 PLAN 行的前置依赖列是否非空。",
          "未核对的计划级依赖可能形成多余等待或使计划执行顺序偏离实际生产关系。",
          "当 PLAN 行第二列的依赖文本非空时触发；不判断依赖对象是否存在或是否必要。",
          "HCYT PLAN 行", _HCYT_SCHEDULE, "rule_excle_plan"),
    _hcyt("hcyt.schedule.plan.upstream_registration", "asset_registry", "接入计划名须登记为上游系统", "err",
          "检查接入计划前缀对应的名称是否存在于上游系统登记元数据。",
          "缺少上游登记会使接入来源无法与资产平台中的系统实体关联。",
          "仅当计划名以 recv_mapping_plan_prefix 开头且不在可读取的上游系统 ID 集合中时触发。",
          "HCYT PLAN 行及上游系统登记", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.recv_mapping_plan_prefix",)),
    _hcyt("hcyt.schedule.plan.missing_send_plan", "metadata", "SEND 作业对应计划须存在于生产", "warn",
          "检查未匹配生产计划的上线计划是否关联到已识别的 SEND 作业。",
          "SEND 作业已进入上线包但生产计划不存在时，调度关系可能无法按预期发布。",
          "当计划名不在 all_plan 元数据中且其大写形式属于从 SEND 作业提取的计划集合时触发。",
          "HCYT PLAN 行及生产计划元数据", _HCYT_SCHEDULE, "rule_excle_plan"),
    _hcyt("hcyt.schedule.plan.missing_dws_plan", "metadata", "DWS 加工计划须存在于生产", "warn",
          "检查未匹配生产计划的计划名是否符合配置的 DWS 计划前后缀模式。",
          "缺少生产计划登记会使上线计划无法对应到既有生产调度实体。",
          "当计划名不在 all_plan 元数据中、不是 SEND 计划，且匹配 missing_plan_warning_patterns 的首个模式时触发。",
          "HCYT PLAN 行及生产计划元数据", _HCYT_SCHEDULE, "rule_excle_plan",
          ("hcyt.schedule.missing_plan_warning_patterns",)),
    _hcyt("hcyt.schedule.plan.missing_production_plan", "metadata", "上线计划须存在于生产", "warn",
          "检查计划名是否存在于生产计划元数据。",
          "生产中没有对应计划时，新作业可能无法挂接到可执行的调度计划。",
          "当计划名不在 all_plan 元数据中，且未命中 SEND 或指定 DWS 计划分支时触发。",
          "HCYT PLAN 行及生产计划元数据", _HCYT_SCHEDULE, "rule_excle_plan"),
    _hcyt("hcyt.schedule.seq.realtime_override", "schedule", "作业流不得覆盖生产实时作业流", "err",
          "检查上线 SEQ 名称是否与生产实时作业流元数据中的名称相同。",
          "同名上线作业流可能覆盖生产实时作业流的调度配置。",
          "当 SEQ 第一列名称出现在 all_real_seq 元数据集合中时触发。",
          "HCYT SEQ 调度表及生产实时作业流元数据", _HCYT_SCHEDULE, "rule_excle_seq"),
    _hcyt("hcyt.schedule.seq.invalid_calendar", "schedule", "作业流日历必须存在于日历元数据", "err",
          "检查 SEQ 执行日历是否存在于生产日历名称集合。",
          "无效日历会使作业流无法按预定日期运行或被调度系统拒绝。",
          "当 SEQ 日历非空、日历元数据集合非空且名称不匹配任何日历时触发。",
          "HCYT SEQ 调度表及生产日历元数据", _HCYT_SCHEDULE, "rule_excle_seq"),
    _hcyt("hcyt.schedule.job.invalid_schema", "schedule", "JOB 调度表至少须有 28 列", "err",
          "检查 JOB DataFrame 是否存在且列数是否达到依赖字段索引所需的 28 列最小值。",
          "列数不足时依赖字段索引无法对应预期列，后续调度判断可能失真。",
          "当传入 df 为 None 或 df.columns 数量小于 28 时触发并提前结束 JOB 表检查；0 行但至少 28 列不会触发。",
          "HCYT JOB Excel 表结构", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.dependency_cycle", "dependency", "上线作业依赖不得形成循环", "err",
          "检查上线作业依赖图中是否存在闭环路径。",
          "循环依赖中的作业会互相等待，导致调度无法找到可执行的起点。",
          "根据上线作业依赖和可用生产依赖构图后，find_cycles 在上线作业节点范围内返回一个或多个环时触发。",
          "HCYT JOB 依赖列及生产作业依赖元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.lowercase_job", "schedule", "JOB 名称必须使用大写字母", "err",
          "检查 JOB 单元格文本是否与其大写形式相同。",
          "大小写不一致可能使作业名与生产登记或依赖配置中的名称无法匹配。",
          "当 JOB 名非空且 job_name.upper() != job_name 时触发。",
          "HCYT JOB Excel 的 JOB 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.lowercase_plan", "schedule", "计划名称必须使用大写字母", "err",
          "检查 JOB 行关联的计划名单元格是否与其大写形式相同。",
          "大小写不一致可能使计划与生产元数据或计划命名规则匹配失败。",
          "当计划名单元格非空且其大写形式与原值不同时触发。",
          "HCYT JOB Excel 的 PLAN 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.lowercase_sequence", "schedule", "作业流名称必须使用大写字母", "err",
          "检查 JOB 行关联的作业流名单元格是否与其大写形式相同。",
          "大小写不一致可能使作业流与生产归属或日历元数据匹配失败。",
          "当作业流名单元格非空且其大写形式与原值不同时触发。",
          "HCYT JOB Excel 的 SEQ 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.disabled_reenable", "metadata", "生产禁用作业不得被意外重新启用", "err",
          "比较上线 JOB 与生产作业状态，检查目标作业是否登记为禁用。",
          "意外重新启用的作业可能恢复已停用的数据处理或下游推送。",
          "当 JOB 名存在于生产状态映射且状态被识别为“禁用”时触发。",
          "HCYT JOB Excel 及生产作业状态元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.disabled_status_values", "hcyt.schedule.enabled_status_values")),
    _hcyt("hcyt.schedule.job.empty_sequence", "schedule", "JOB 必须登记所属作业流", "err",
          "检查 JOB 行的 SEQ 单元格是否为空字符串。",
          "没有作业流归属的 JOB 可能无法按计划执行，也难以与生产调度结构核对。",
          "当去除首尾空格后的 SEQ 值为空时触发。",
          "HCYT JOB Excel 的 SEQ 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.realtime_priority", "schedule", "实时作业优先级须匹配配置值", "err",
          "检查 SEQ 属于生产实时序列或包含配置关键字的 JOB，其优先级是否属于 realtime_priority_values。",
          "优先级不符合当前配置约定可能使实时作业排队时点偏离预期。",
          "当 SEQ 名称属于 all_real_seq 元数据集合或包含 realtime_sequence_keyword，且 PRIORITY 字符串不在 realtime_priority_values 中时触发。",
          "HCYT JOB Excel 的 SEQ / JOB / PRIORITY 列及实时序列元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.real_job_plan_names", "hcyt.schedule.realtime_sequence_keyword",
           "hcyt.schedule.realtime_priority_values")),
    _hcyt("hcyt.schedule.job.description", "schedule", "作业描述必须包含有效加工说明", "err",
          "按配置的最少中文字符、噪声短语和无效值规则判断 JOB 描述是否有实质内容。",
          "描述不足时，审核人员无法从调度表判断作业用途及其处理范围。",
          "当 has_meaningful_job_description 对描述、作业名和配置返回 false 时触发。",
          "HCYT JOB Excel 的 DESCRIPTION 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.description_validation",)),
    _hcyt("hcyt.schedule.job.realtime_calendar", "schedule", "指定实时计划的日历须匹配配置值", "err",
          "检查 realtime_calendar_plans 中计划的 JOB 日历是否等于 realtime_calendar_value。",
          "日历与当前配置不一致时，作业可能按非预期频率运行。",
          "当 PLAN 名精确出现在 realtime_calendar_plans 且 CALENDAR 与 realtime_calendar_value 不同时触发；比较按当前配置值执行。",
          "HCYT JOB Excel 的 PLAN / CALENDAR 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.realtime_calendar_plans", "hcyt.schedule.realtime_calendar_value")),
    _hcyt("hcyt.schedule.job.invalid_calendar", "metadata", "JOB 执行日历必须存在于日历元数据", "err",
          "检查非空 JOB 日历是否存在于生产日历名称集合。",
          "调度系统无法识别的日历可能使作业不运行或被分配错误的运行日期。",
          "当有效日历元数据非空且 JOB 日历不在集合中时触发；元数据集合为空时跳过此判断。",
          "HCYT JOB Excel 的 CALENDAR 列及生产日历元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.execution_domain", "schedule", "指定计划的作业不得使用禁用执行域", "err",
          "检查执行域是否等于禁用域，且计划名包含配置的禁用计划关键字。",
          "在这些计划中使用禁用执行域可能使作业提交到错误的运行环境。",
          "当 domain == forbidden_domain 且 plan_name 命中任一 forbidden_domain_plan_keywords 时触发。",
          "HCYT JOB Excel 的 PLAN / DOMAIN 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_domain", "hcyt.schedule.forbidden_domain_plan_keywords")),
    _hcyt("hcyt.schedule.job.invalid_domain", "schedule", "作业执行域必须属于允许列表", "err",
          "检查 JOB 执行域是否包含在 configured allowed_domains 中。",
          "未受支持的执行域可能使作业调度到不存在或未授权的运行环境。",
          "当 JOB 的 DOMAIN 值不属于 allowed_domains 时触发。",
          "HCYT JOB Excel 的 DOMAIN 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.allowed_domains",)),
    _hcyt("hcyt.schedule.job.dwd_sequence", "schedule", "DWD 计划须使用允许的作业流名", "err",
          "检查 DWD 计划下的 SEQ 是否属于配置的 DWD 作业流名称。",
          "作业流与计划层级不一致会使任务进入错误批次或无法按层级维护。",
          "当 PLAN 包含 DWD 且 SEQ 不在 sequence_name_rules.DWD 中时触发。",
          "HCYT JOB Excel 的 PLAN / SEQ 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.sequence_name_rules.DWD",)),
    _hcyt("hcyt.schedule.job.dwp_sequence", "schedule", "DWP 计划须使用允许的作业流名", "err",
          "检查 DWP 计划下的 SEQ 是否属于配置的 DWP 作业流名称。",
          "作业流与计划层级不一致会使任务进入错误批次或无法按层级维护。",
          "当 PLAN 包含 DWP 且 SEQ 不在 sequence_name_rules.DWP 中时触发。",
          "HCYT JOB Excel 的 PLAN / SEQ 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.sequence_name_rules.DWP",)),
    _hcyt("hcyt.schedule.job.dwm_sequence", "schedule", "DWM 计划须使用允许的作业流名", "err",
          "检查 DWM 计划下的 SEQ 是否属于配置的 DWM 作业流名称。",
          "作业流与计划层级不一致会使任务进入错误批次或无法按层级维护。",
          "当 PLAN 包含 DWM 且 SEQ 不在 sequence_name_rules.DWM 中时触发。",
          "HCYT JOB Excel 的 PLAN / SEQ 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.sequence_name_rules.DWM",)),
    _hcyt("hcyt.schedule.job.missing_dwf_dependency", "dependency", "命中 DWF 关键字且依赖为空的 JOB 须复核", "err",
          "检查 DEPENDENCIES 为空且 JOB 名包含配置的第一个依赖关键字的行。",
          "若命中作业确需上游数据，缺少前置依赖可能使其在来源数据未就绪时启动；名称命中不证明其业务类型。",
          "当依赖文本为空且 JOB 名包含 dependency_required_job_keywords[0] 时触发；按配置子串匹配，不核实 JOB 是否实际属于 DWF。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.dependency_required_job_keywords",)),
    _hcyt("hcyt.schedule.job.missing_dwo_dependency", "dependency", "命中 DWO 关键字且依赖为空的 JOB 须复核", "err",
          "检查依赖为空、未命中前置 DWF 关键字或配置例外，且 JOB 名包含第二个配置依赖关键字的行。",
          "若命中作业确需上游数据，缺少依赖可能使其读取不完整数据；名称命中不证明其业务类型。",
          "当依赖文本为空、JOB 名未命中 dependency_required_job_keywords[0] 和 dependency_exceptions，且命中 dependency_required_job_keywords[1] 时触发；按配置子串匹配。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.dependency_required_job_keywords", "hcyt.schedule.dependency_exceptions")),
    _hcyt("hcyt.schedule.job.missing_dependency", "dependency", "命中配置关键字且依赖为空的 JOB 须复核", "err",
          "检查依赖为空、未命中 DWF/DWO 前置分支或配置例外，且 JOB 名命中后续配置依赖关键字的行。",
          "若命中作业确需上游数据，缺少依赖可能使其在输入未准备时运行；名称命中不证明业务类型。",
          "当依赖为空、未命中前置关键字分支及 dependency_exceptions，并命中 dependency_required_job_keywords[2:] 中首个关键字时触发；按配置子串匹配。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.dependency_required_job_keywords", "hcyt.schedule.dependency_exceptions")),
    _hcyt("hcyt.schedule.job.chinese_dependency_colon", "dependency", "作业依赖不得使用中文冒号", "err",
          "检查 DEPENDENCIES 单元格是否包含中文全角冒号。",
          "依赖解析按半角分隔符拆分时，全角冒号可能使作业名无法提取和匹配。",
          "当 DEPENDENCIES 文本包含字符“：”时触发。",
          "HCYT JOB Excel 的 DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.provision_dependency", "dependency", "指定执行域的加工 JOB 不得依赖卸数 JOB", "err",
          "检查指定执行域作业的依赖项是否包含配置的卸数作业关键字。",
          "加工任务直接依赖卸数任务可能绕过预期的数据装载与加工顺序。",
          "当当前作业 DOMAIN 等于 forbidden_domain 且任一解析出的前置 JOB 包含 provision_job_keyword 时触发。",
          "HCYT JOB Excel 的 DOMAIN / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_domain", "hcyt.schedule.provision_job_keyword")),
    _hcyt("hcyt.schedule.job.missing_production_dependency", "dependency", "作业前置依赖必须存在于生产或上线清单", "err",
          "检查解析出的前置 JOB 名是否存在于生产作业或当前上线作业集合。",
          "引用不存在的前置作业会使调度等待一个永远不会完成的节点。",
          "当非空前置 JOB 不在 yilai_job 集合中时触发；该集合由生产元数据和当前作业名组成。",
          "HCYT JOB Excel 及生产作业元数据", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.self_dependency", "dependency", "作业不得依赖自身或所属计划", "err",
          "检查解析出的前置 JOB 标识是否等于当前 JOB 名或计划名。",
          "自依赖或将计划名误写为作业依赖会造成依赖图错误或循环等待。",
          "当任一解析出的 job_real 与 job_name 或 plan_name 相等时触发。",
          "HCYT JOB Excel 的 JOB / PLAN / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.realtime_plan_dependency", "dependency", "实时计划不得依赖普通计划作业", "err",
          "比较实时计划的前置作业所属计划是否也具有实时后缀。",
          "实时任务等待普通批次计划可能错过预期的实时出数时间。",
          "当当前计划以 realtime_plan_suffix 结尾，前置 JOB 与所属计划均可解析，且前置计划不以该后缀结尾时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.realtime_plan_suffix",)),
    _hcyt("hcyt.schedule.job.late_plan_dependency", "dependency", "作业不得依赖未豁免的晚执行计划", "warn",
          "检查前置作业的生产所属计划是否在晚执行计划名单中。",
          "上游计划启动较晚可能使当前作业无法在要求的出数时点前完成。",
          "当前计划不在 late_plan_exceptions 且前置计划属于 late_plan_names 时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.late_plan_names", "hcyt.schedule.late_plan_exceptions")),
    _hcyt("hcyt.schedule.job.forbidden_realtime_dependency", "dependency", "普通作业不得依赖禁用实时计划", "err",
          "检查前置作业所属计划是否等于配置的第一个禁止依赖计划。",
          "依赖特殊实时计划可能使普通批次与特定业务调度相互耦合。",
          "当前计划不等于 realtime_dependency_exception 且前置计划等于 forbidden_dependency_plans[0] 时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.realtime_dependency_exception", "hcyt.schedule.forbidden_dependency_plans")),
    _hcyt("hcyt.schedule.job.forbidden_legacy_dependency", "dependency", "作业不得依赖指定旧绩效计划", "err",
          "检查前置作业所属计划是否等于配置的第二个禁止依赖计划。",
          "继续依赖已指定的旧绩效计划会使新作业受旧批次状态和数据口径影响。",
          "当前置计划等于 forbidden_dependency_plans[1] 时触发。",
          "HCYT JOB Excel 及生产计划归属元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_dependency_plans",)),
    _hcyt("hcyt.schedule.job.missing_production_plan", "metadata", "JOB 计划名须在生产或上线计划集合中", "err",
          "检查 JOB 行的计划名是否出现在传入的 r_plan 集合中；该集合通常含生产计划和本次 PLAN 文件中的计划。",
          "计划名不在本次检查集合中时，JOB 可能无法关联到本次识别的调度计划。",
          "当 plan_name 不在 r_plan 中时触发；若未传入 r_plan，则从 all_plan 元数据构造集合。",
          "HCYT JOB Excel 及生产/上线计划清单", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.parameter_space", "schedule", "指定卸数域的 JOB 参数不得含空格", "err",
          "检查指定执行域 JOB 的参数文本是否包含 ASCII 空格。",
          "参数解析器可能将空格切分为多个参数，导致过滤条件或路径值被错误解释。",
          "当 DOMAIN 等于 forbidden_domain 且参数文本包含普通空格时触发。",
          "HCYT JOB Excel 的 DOMAIN / PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.forbidden_domain",)),
    _hcyt("hcyt.schedule.job.parameter_tab", "schedule", "JOB 参数不得含 TAB 字符", "err",
          "检查 JOB 参数字段是否包含 TAB 字符。",
          "TAB 可能使调度参数解析结果与表格中看到的内容不一致。",
          "当 PARAMETERS 单元格包含任意制表符时触发，不限于指定执行域。",
          "HCYT JOB Excel 的 PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.duplicate_export_path", "schedule", "卸数路径不得与其他 JOB 重复", "err",
          "从卸数参数中提取 outfile，并与生产 JOB 的 outfile 映射比较。",
          "多个作业写入同一路径可能相互覆盖，使下游读取到错误作业生成的文件。",
          "当计划名包含 recv_plan_keyword、参数含 outfile= 且生产映射显示该路径归属其他 JOB 时触发。",
          "HCYT JOB Excel 的 PLAN / PARAMETERS 列及生产 outfile 元数据", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.recv_plan_keyword",)),
    _hcyt("hcyt.schedule.job.export_flags", "schedule", "卸数参数不得启用全字段或源数据获取标记", "err",
          "检查指定卸数计划的参数是否包含 selflg=N 或 metaflg=Y。",
          "不符合约定的字段/源数据选项可能扩大导出内容或改变卸数接口语义。",
          "当计划名包含 recv_plan_keyword 且参数包含任一指定字面量时触发。",
          "HCYT JOB Excel 的 PLAN / PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.recv_plan_keyword",)),
    _hcyt("hcyt.schedule.job.full_export", "schedule", "DIDP 参数未命中来源或过滤标记须复核", "warn",
          "检查 PROGRAM 和 PARAMETERS 单元格中的指定字符串，不解析卸数配置或实际导出范围。",
          "若程序确为该 DIDP 版本且未设置来源或过滤参数，导出范围可能较大；文本条件不能证明实际数据量。",
          "当 PROGRAM 大小写敏感地包含 DIDP_DATA_PROVISION.1.0，且 PARAMETERS 大小写敏感地同时不包含 srcfile 与 -filt 时触发。",
          "HCYT JOB Excel 的 PROGRAM / PARAMETERS 列", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.production_plan_mismatch", "metadata", "上线 JOB 计划名须与生产映射核对", "err",
          "比较上线 JOB 计划名与生产映射中的同名 JOB 计划名；缺少映射也会视为不相等。",
          "计划归属变化可能使已有 JOB 进入不同批次并影响执行顺序；无映射时需先核对元数据完整性。",
          "当 JOB 名存在于生产作业集合 r_job、SEQ 不等于字符串 0，且 r_planjob.get(job_name) 与上线 PLAN 不同时触发；缺少映射（None）也满足不等条件。",
          "HCYT JOB Excel 与生产 JOB 计划映射", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.production_sequence_mismatch", "metadata", "上线 JOB 作业流名须与生产映射核对", "err",
          "比较上线 JOB 的 SEQ 与生产映射中的同名 JOB 作业流名；缺少映射也会视为不相等。",
          "作业流归属变化可能使已有 JOB 按不同日历或调度顺序执行；无映射时需先核对元数据完整性。",
          "当 JOB 名存在于生产作业集合 r_job、上线 SEQ 不等于字符串 0，且 r_seqjob.get(job_name) 与上线 SEQ 不同时触发；缺少映射（None）也满足不等条件。",
          "HCYT JOB Excel 与生产 JOB 作业流映射", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.sequence_plan_mismatch", "metadata", "上线 SEQ 计划名须与生产映射核对", "err",
          "比较上线 SEQ 的计划名与生产映射中的计划名；缺少映射也会视为不相等。",
          "将已有作业流挂到不同计划可能改变该作业流下 JOB 的运行时点；无映射时需先核对元数据完整性。",
          "当 SEQ 存在于生产集合 r_seq、SEQ 不等于字符串 0，且 r_planseq.get(seq_name) 与上线 PLAN 不同时触发；缺少映射（None）也满足不等条件。",
          "HCYT JOB Excel 与生产 SEQ 计划映射", _HCYT_SCHEDULE, "rule_excle_job"),
    _hcyt("hcyt.schedule.job.required_predecessors", "dependency", "指定 JOB 需复核配置要求的前置作业", "err",
          "检查指定 JOB 是否需要复核其前置作业关系。",
          "若指定 JOB 缺少其业务所需来源作业，可能在输入数据尚未准备时执行。",
          "当 JOB 名命中配置的指定作业键时触发；当前实现不比较依赖列是否包含配置的前置 JOB 列表。",
          "HCYT JOB Excel 的 JOB / DEPENDENCIES 列", _HCYT_SCHEDULE, "rule_excle_job",
          ("hcyt.schedule.required_predecessors",)),
    _hcyt("hcyt.schedule.job.push_job_missing", "asset_registry", "SEND 作业必须登记下游推送关系", "warn",
          "检查识别为 SEND 类型的 JOB 是否存在下游推送作业登记。",
          "作业产出成功并不代表下游交付关系已登记；缺少登记会使接收方不在正式交付链路中。",
          "当 SEND 参数识别成功、下游推送元数据可读取，且登记中找不到对应 job_code 时触发。",
          "HCYT SEND JOB 及下游推送登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),
    _hcyt("hcyt.schedule.job.push_job_disabled", "asset_registry", "SEND 作业的下游推送登记必须启用", "warn",
          "检查匹配的下游推送作业登记中是否至少有一条状态为启用。",
          "登记已停用时，作业运行结果不会按该登记关系交付给下游系统。",
          "当 SEND JOB 找到登记记录，但所有匹配记录的状态都不是 Y 时触发。",
          "HCYT SEND JOB 及下游推送登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),
    _hcyt("hcyt.schedule.job.push_system_missing", "asset_registry", "SEND 作业必须登记有效下游系统", "warn",
          "检查匹配的下游推送登记是否都具有非空下游系统代码。",
          "没有系统代码的登记无法确定数据交付对象。",
          "当匹配登记记录中至少有一条 system_code 为空时触发。",
          "HCYT SEND JOB 及下游推送系统登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),
    _hcyt("hcyt.schedule.job.push_system_disabled", "asset_registry", "SEND 作业关联的下游系统必须启用", "warn",
          "检查具有非空系统代码的匹配记录中是否至少存在一条 enabled 系统状态。",
          "所有关联系统均停用时，推送登记无法将作业结果交付到可用接收方。",
          "当存在有效系统代码，但所有有效记录的状态均不为 enabled 时触发。",
          "HCYT SEND JOB 及下游系统登记", _HCYT_SCHEDULE, "_add_push_registration_findings"),

    # NUPS rules. The SQL patterns remain workflow-specific even when their wording resembles HCYT.
    _nups("nups.ddl.temp_table_name", "ddl", "临时表名须匹配配置前缀", "err",
          "检查提取出的临时表或 TMP schema 表名是否以当前配置的临时表前缀开头。",
          "临时对象未使用约定前缀，可能被误认为持久业务表或无法按临时表约定管理。",
          "CREATE TABLE 对象由原始 SQL 文本正则提取，ALTER TABLE 对象由正则提取；临时状态由对象 schema 或所在语句文本中的 TEMP 标记判断，名称未匹配任一配置前缀时触发。解析不排除注释或字符串；加工程序结果表名另由路径父目录解析。",
          "NUPS SQL 中正则提取的表对象或加工程序路径结果表", _NUPS, "check_table_name_rule",
          ("nups.file_rules.program_table_name.directory_schema_prefix",)),
    _nups("nups.ddl.table_name", "ddl", "分层表名须匹配 schema 配置前缀", "err",
          "检查正则提取出的 DDL 表名及加工程序路径解析出的结果表名是否以所属 schema 的配置前缀开头。",
          "表名层级与前缀不一致会使维护人员和下游作业难以识别其数据层。",
          "CREATE/ALTER TABLE 候选由原始 SQL 文本正则提取；另检查加工程序父目录名解析出的结果表。仅对配置了前缀的 schema 判断；SQL 文本提取不排除注释或字符串。",
          "NUPS SQL 中正则提取的表对象或加工程序路径结果表", _NUPS, "check_table_name_rule",
          ("nups.file_rules.program_table_name.directory_schema_prefix",)),
    _nups("nups.ddl.column_comment", "ddl", "指定 schema 的字段须提供可识别注释", "err",
          "检查正则提取出的 CREATE TABLE 字段和 ALTER TABLE ADD COLUMN 字段是否含行内 COMMENT 或匹配的 COMMENT ON COLUMN。",
          "未提取到字段注释时，下游使用者难以从表结构确认字段含义；规则不评价注释内容质量。",
          "仅对 COLUMN_COMMENT_REQUIRED_SCHEMAS 中的表检查；字段定义、ALTER ADD COLUMN 和 COMMENT ON COLUMN 通过文本正则/分隔逻辑提取，未提取到任一种非空注释时触发。原始文本中的注释或字符串可能影响匹配。",
          "NUPS SQL 中可提取的字段定义与 COMMENT 语句", _NUPS, "check_column_comment_rule"),
    _nups("nups.sql.create_view", "sql", "NUPS SQL 文本中的 CREATE VIEW 模式须复核", "err",
          "在 NUPS SQL 全文中用正则搜索 CREATE [OR REPLACE] VIEW 后接对象名的文本模式。",
          "若命中内容是实际视图定义，新增或改变共享数据库对象可能影响其他调用方；文本匹配不证明语句有效。",
          "对整个 SQL 文本大写化后匹配 CREATE [OR REPLACE] VIEW <简单或 schema 限定名称>；不剔除注释和字符串。",
          "NUPS SQL 文件全文", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.create_function", "sql", "NUPS SQL 文本中的 CREATE FUNCTION 模式须复核", "err",
          "在 NUPS SQL 全文中用正则搜索 CREATE [OR REPLACE] FUNCTION 后接对象名的文本模式。",
          "若命中内容是实际函数定义，函数变化可能影响调用方结果或依赖；文本匹配不证明语句有效。",
          "对整个 SQL 文本大写化后匹配 CREATE [OR REPLACE] FUNCTION <简单或 schema 限定名称>；不剔除注释和字符串。",
          "NUPS SQL 文件全文", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.use_view", "sql", "NUPS SQL 文本候选名称命中登记视图须复核", "err",
          "从 NUPS SQL 文本提取点分隔名称候选，并与已登记视图名称匹配；不解析 SQL 对象依赖。",
          "若命中项确为视图引用，视图定义或来源变化可能改变查询结果；文本候选匹配本身不证明实际依赖。",
          "仅当视图元数据可读取时，对 find_dot_strings(data.upper()) 返回的候选与登记视图名比较；候选仅保留指定 DWS schema 前缀（DM、DWA、DWD、DWUPRR、DWM、DWP、DWO、DWF），原文注释和字符串也可能命中。",
          "NUPS SQL 全文及视图元数据", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.use_function", "sql", "NUPS SQL 文本命中登记函数调用模式须复核", "err",
          "用正则在 NUPS SQL 全文中搜索登记函数名后跟左括号的模式，不解析 SQL 调用。",
          "若命中项确为数据库函数调用，函数实现变化可能改变结果或运行成本；文本匹配不能证明调用会执行。",
          "仅当函数元数据可读取时，按大小写不敏感的函数名\\s*\\(模式扫描 SQL 全文；注释和字符串也可能命中。",
          "NUPS SQL 全文及函数元数据", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.too_many_lines", "sql", "NUPS SQL 文件不得超过 20,000 行", "err",
          "检查按换行符拆分后的 NUPS SQL 行数是否大于 20,000。",
          "单文件体量过大时，审查变更和定位问题需要在大量文本中搜索。",
          "当 len(data.split('\\n')) > 20000 时触发；空行也计入行数。",
          "NUPS SQL 文件", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.alter_statement", "sql", "NUPS SQL 文本中的 ALTER 字样须复核", "err",
          "检查 NUPS SQL 全文是否包含 ALTER 子串，不解析语句边界。",
          "若命中内容是实际 ALTER 语句，其对象结构或属性变化可能造成兼容性问题；文本命中不证明执行语句。",
          "当 SQL 全文转为大写后包含 ALTER 时触发；注释和字符串也可能命中。",
          "NUPS SQL 文件全文", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.dwm_operation", "sql", "NUPS SQL 文本中的 DWM. 标记须复核", "err",
          "检查 NUPS SQL 全文是否包含 DWM. 子串，不区分读写操作。",
          "若命中内容对应模型层对象操作或引用，可能影响已发布模型和下游报表；该子串不证明实际对象或操作。",
          "当 SQL 全文（包括注释和字符串）转为大写后包含 DWM. 时触发。",
          "NUPS SQL 文件全文", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.legacy_group_clause", "sql", "NUPS SQL 文本中的 TO GROUP GROUP_VERSION1 须复核", "err",
          "检查 NUPS SQL 全文是否包含 TO GROUP GROUP_VERSION1 字符串，不解析 GROUP 子句。",
          "若命中内容是实际旧版 GROUP 语句，可能与当前数据库部署规则不兼容；文本匹配不证明语句有效。",
          "当 SQL 全文转为大写后包含 TO GROUP GROUP_VERSION1 时触发；不排除注释和字符串。",
          "NUPS SQL 文件全文", _NUPS, "_legacy_rule_dws"),
    _nups("nups.sql.legacy_marker", "sql", "NUPS SQL 文本命中已配置遗留标记须复核", "err",
          "检查 NUPS SQL 全文是否包含配置的遗留标记字符串，并按配置排除项过滤。",
          "若命中内容对应实际旧取数引用，可能继续读取过期来源；字符串命中本身不能证明其用途。",
          "将 SQL 全文转为大写后，命中任一非空配置 marker 且未命中其 excludes 时触发；不排除注释和字符串。",
          "NUPS SQL 文件全文", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.legacy_markers",)),
    _nups("nups.sql.protected_code_table", "asset_registry", "NUPS SQL 文本命中受保护码值表名称须复核", "err",
          "检查 NUPS SQL 全文是否包含任一配置的受保护码值表名称，不解析表引用或读写操作。",
          "若命中内容对应对受保护码值表的实际写入，可能改变共享码值映射；单纯文本命中不能证明发生修改。",
          "将 SQL 全文转为大写后搜索配置表名子串；不区分读写，也不排除注释和字符串。",
          "NUPS SQL 全文及受保护码值表配置", _SHARED_DWS, "run_configured_dws_sql_reviews",
          ("dws.sql_review.protected_code_tables",)),
    _nups("nups.program.create_view", "python", "NUPS 程序文本中的 CREATE VIEW 模式须复核", "err",
          "在 NUPS 加工程序全文中用正则搜索 CREATE [OR REPLACE] VIEW 后接对象名的文本模式。",
          "若命中内容是实际视图定义，新增或改变共享数据库对象可能影响其他调用方；文本匹配不证明语句有效。",
          "对整个程序源文本大写化后匹配 CREATE [OR REPLACE] VIEW <简单或 schema 限定名称>；不剔除注释和字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.create_function", "python", "NUPS 程序文本中的 CREATE FUNCTION 模式须复核", "err",
          "在 NUPS 加工程序全文中用正则搜索 CREATE [OR REPLACE] FUNCTION 后接对象名的文本模式。",
          "若命中内容是实际函数定义，函数变化可能影响调用方结果或依赖；文本匹配不证明语句有效。",
          "对整个程序源文本大写化后匹配 CREATE [OR REPLACE] FUNCTION <简单或 schema 限定名称>；不剔除注释和字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.for_loop", "python", "报送程序不得包含 FOR I IN 文本模式", "err",
          "检查程序文本大写化后是否包含 FOR I IN 子串。",
          "若命中内容是实际循环，循环体重复执行查询或写入可能延长作业时间；文本命中不证明其为 Python 循环。",
          "当整个程序源文本转为大写后包含连续文本 FOR I IN 时触发；不解析 Python 语法，注释和字符串也可能命中。",
          "NUPS Python 加工文件", _NUPS, "rule_dws_py"),
    _nups("nups.program.character_varying_length", "python", "NUPS 程序文本中的 CHARACTER VARYING( 模式须复核", "err",
          "检查 NUPS 加工程序全文是否包含 CHARACTER VARYING( 字符串，不解析字段声明。",
          "若该模式属于实际定长字段声明，字段长度可能无法容纳较长值；命中本身不能证明发生截断或写入失败。",
          "对整个程序源文本转为大写后搜索 CHARACTER VARYING(；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.varchar2_length", "python", "NUPS 程序文本中的 VARCHAR2( 模式须复核", "err",
          "检查 NUPS 加工程序全文是否包含 VARCHAR2( 字符串，不解析字段声明。",
          "若该模式属于实际定长字段声明，字段长度可能无法容纳较长值；命中本身不能证明发生截断或写入失败。",
          "对整个程序源文本转为大写后搜索 VARCHAR2(；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.nested_nvl", "python", "NUPS 程序文本中的 NVL(NVL( 模式须复核", "err",
          "检查 NUPS 加工程序全文是否包含 NVL(NVL( 字符串，不解析函数调用结构。",
          "若命中内容是实际嵌套空值处理，取值回退路径可能较难核对；文本匹配本身不证明存在嵌套函数调用。",
          "对整个程序源文本转为大写后搜索 NVL(NVL(；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.nested_coalesce", "python", "NUPS 程序文本中的 COALESCE(COALESCE( 模式须复核", "err",
          "检查 NUPS 加工程序全文是否包含 COALESCE(COALESCE( 字符串，不解析函数调用结构。",
          "若命中内容是实际嵌套空值处理，取值优先级可能较难核对；文本匹配本身不证明存在嵌套函数调用。",
          "对整个程序源文本转为大写后搜索 COALESCE(COALESCE(；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.distinct_review", "python", "NUPS 程序文本命中 DISTINCT 须核对去重范围", "err",
          "检查 NUPS 加工程序全文是否包含 DISTINCT 字符串，不解析查询语句或判断去重是否必要。",
          "若 DISTINCT 位于实际查询中，不必要的去重可能增加排序或哈希开销；不恰当的去重也可能掩盖关联产生的重复行。",
          "程序源文本转为大写后包含 DISTINCT 即触发；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.legacy_outer_join", "python", "NUPS 程序文本中的 (+) 模式须复核", "err",
          "检查 NUPS 加工程序源文本是否包含 (+) 字符串，不解析外连接语法。",
          "若命中内容属于旧式外连接，条件分布不直观，修改过滤条件时可能改变保留行语义；注释或字符串命中不代表查询使用该写法。",
          "整个程序源文本包含 (+) 即触发；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.affected_rows_log", "python", "NUPS 程序文本须包含影响条数标记", "err",
          "检查 NUPS 加工程序源文本是否包含“影响条数”字符串，不验证日志调用。",
          "缺少该文本标记时，审核人员较难从源文件中定位影响行数日志；标记存在也不证明日志会执行或数量准确。",
          "当整个源文本不含“影响条数”时触发；不检查字符串是否位于可执行日志语句中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.legacy_group_clause", "python", "NUPS 程序文本中的 TO GROUP GROUP_VERSION1 模式须复核", "err",
          "检查 NUPS 加工程序源文本是否包含 TO GROUP GROUP_VERSION1 字符串，不解析 GROUP 子句。",
          "若命中内容是实际旧版 GROUP 语句，可能与当前数据库部署规则不兼容；文本匹配不证明语句会执行。",
          "整个程序源文本转为大写后包含 TO GROUP GROUP_VERSION1 时触发；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.hardcoded_date", "python", "NUPS 程序文本中的日期候选须复核", "err",
          "在 NUPS 加工程序源文本第 1001 个字符起搜索带引号的 YYYYMMDD 或 YYYY-MM-DD 日期候选，并仅保留可解析且年份在 1900–3000 的值。",
          "若候选是实际查询中的固定日期，可能使后续批次处理旧期间或遗漏新期间；正则命中不证明日期用途。",
          "对 data[1000:] 调用 find_hardcoded_dates；扫描源文件尾段而非提取 SQL，匹配可出现在注释或字符串中。",
          "NUPS Python 加工源文件第 1001 字符起", _NUPS, "rule_dws_py"),
    _nups("nups.program.use_view", "python", "NUPS 程序文本候选名称命中登记视图须复核", "err",
          "从 NUPS 程序文本提取的对象名称候选中查找与视图元数据匹配的名称，不解析 SQL 对象依赖。",
          "若命中项确为视图引用，视图定义或来源变化可能改变报送结果；候选匹配本身不能证明实际依赖。",
          "仅当视图元数据可读取时检查 data[1000:] 经 extract_tables 与 find_dot_strings 提取的候选；排除内置名后与登记视图名匹配即触发，结果表在此匹配后才被过滤，注释和字符串也可能命中。",
          "NUPS Python 加工源文件第 1001 字符起及视图元数据", _NUPS, "rule_dws_py"),
    _nups("nups.program.use_function", "python", "NUPS 程序文本命中登记函数调用模式须复核", "err",
          "用正则在 NUPS 加工程序源文本中搜索登记函数名后跟左括号的模式，不解析 SQL 或 Python 调用。",
          "若命中项确为数据库函数调用，函数实现变化可能改变报送结果或运行成本；文本模式不能证明调用会执行。",
          "仅当函数元数据可读取时，按大小写不敏感的函数名\\s*\\(模式扫描整个源文本；注释和字符串也可能命中。",
          "NUPS Python 加工源文件全文及函数元数据", _NUPS, "rule_dws_py"),
    _nups("nups.program.partition_rollback", "python", "结果表分区状态须与回滚步骤文本核对", "err",
          "比较结果表分区数是否大于 0，与源文本是否同时匹配 rollback_deal 定义和分区操作模式。",
          "分区表缺少对应回滚步骤可能留下不完整结果；非分区表却包含该步骤也可能执行不符预期。",
          "结果表路径可解析时查询分区数；将分区数大于 0 的布尔值与全文同时命中 DEF ROLLBACK_DEAL( 及 TRUNCATE/ADD/DROP/SPLIT PARTITION 的布尔值比较，不同时触发。正则不排除注释或字符串。",
          "NUPS Python 加工源文件及结果表分区元数据", _NUPS, "rule_dws_py"),
    _nups("nups.program.missing_schema", "python", "NUPS 程序中的未限定名称候选须复核", "err",
          "检查从程序源文本提取、且未被排除为内置名、结果表或登记函数的名称候选是否含点号。",
          "若命中项确为未限定表引用，默认 schema 可能使不同运行账户解析到不同对象；候选误报需先确认其 SQL 角色。",
          "仅处理 data[1000:]：extract_tables 与 find_dot_strings 从文本提取候选，过滤后不含点号即触发；不做 SQL 解析，CTE、注释或字符串可误命中。",
          "NUPS Python 加工源文件第 1001 字符起及候选对象名", _NUPS, "rule_dws_py"),
    _nups("nups.program.forbidden_table", "metadata", "NUPS 程序文本命中禁用表名须复核", "err",
          "检查禁用表元数据中的名称是否以大小写不敏感方式出现在 NUPS 加工程序源文本中，不解析 SQL 表引用。",
          "若命中名称属于实际来源引用，可能使用已列入禁用清单的数据；文本命中也可能来自注释或字符串。",
          "当 all_sstb 元数据读取成功且任一表名（忽略大小写）是整个源文本的子串时触发；不区分代码、注释、字符串或 SQL 语句。",
          "NUPS Python 加工源文件全文及禁用表元数据", _NUPS, "rule_dws_py"),
    _nups("nups.program.scalar_subquery", "python", "NUPS 程序文本中的 =(SELECT 模式须复核", "err",
          "检查去除普通空格和 TAB 后的整个 NUPS 程序源文本是否包含 =(SELECT 字符串。",
          "若该文本属于等号右侧标量子查询且结果多于一行，执行可能失败；检测器不判断语法或查询基数。",
          "对整个源文本移除普通空格和 TAB 并转为大写后搜索 =(SELECT；不移除换行，也不排除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.in_subquery", "python", "NUPS 程序文本中的 IN(SELECT 模式须复核", "err",
          "检查去除普通空格和 TAB、移除 JOIN(SELECT 后的整个 NUPS 程序源文本是否包含 IN(SELECT 字符串。",
          "若命中内容属于大型实际子查询，可能扩大扫描范围或增加执行时间；文本匹配不证明查询规模或计划成本。",
          "对整个源文本移除普通空格和 TAB 并转为大写，再删除 JOIN(SELECT 子串；剩余文本包含 IN(SELECT 即触发，不排除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.end_dt_range", "python", "NUPS 程序文本中的 .END_DT>= 模式须复核", "err",
          "检查去除普通空格和 TAB 后的 NUPS 程序源文本是否包含 .END_DT>= 字符串。",
          "若该模式是拉链表的有效期条件，边界写法可能影响有效记录筛选；命中本身不确认字段来源或比较语义。",
          "对整个程序源文本移除普通空格和 TAB 并转为大写后搜索 .END_DT>=；不解析 SQL，也不排除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_to_date", "python", "D_DATE=TO_DATE(' 文本模式须复核", "err",
          "在 NUPS 加工程序源文本中搜索 D_DATE 标识符后跟 TO_DATE(' 的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，对日期列套用转换可能影响过滤或分区裁剪；命中本身不能证明这一语义。",
          "对整个 NUPS 程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界、等号、TO_DATE( 和单引号之间允许空白；不剔除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_literal", "python", "D_DATE=DATE' 文本模式须复核", "err",
          "在 NUPS 加工程序源文本中搜索 D_DATE 标识符后跟 DATE 字面量的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，字面量形式可能不符合项目日期约定；命中本身不能证明对象或过滤意图。",
          "对整个 NUPS 程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界、等号及 DATE' 之间允许空白；不剔除注释或字符串，也不推断日期覆盖范围。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_function", "python", "DATE(D_DATE) 文本模式须复核", "err",
          "在 NUPS 加工程序源文本中搜索 DATE 函数参数包含 D_DATE 标识符的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，对日期列应用函数可能影响过滤或分区裁剪；命中本身不能证明这一语义。",
          "对整个 NUPS 程序源文本执行大小写不敏感正则匹配：DATE( 可含空白，参数允许可选 schema 限定的 D_DATE 标识符；不剔除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.to_date_d_date", "python", "TO_DATE(D_DATE, 文本模式须复核", "err",
          "在 NUPS 加工程序源文本中搜索 TO_DATE 参数以 D_DATE 标识符开头的模式；不判断其是否位于有效 SQL 或主题表条件中。",
          "若该模式位于实际日期过滤表达式中，字符串转换可能影响过滤或分区裁剪；命中本身不能证明这一语义。",
          "对整个 NUPS 程序源文本执行大小写不敏感正则匹配：TO_DATE( 可含空白，参数允许可选 schema 限定的 D_DATE 标识符并随后出现逗号；不剔除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_less_than", "python", "D_DATE 小于比较文本须复核", "err",
          "在 NUPS 加工程序源文本中搜索 D_DATE 标识符后跟小于号的模式；不判断对象是否为主题表或比较是否属于有效 SQL。",
          "若命中内容实际是全量数据的日期过滤条件，边界可能排除所需记录；检测器无法确认表类型或业务日期约定。",
          "对整个 NUPS 程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界后允许空白再跟 <；也会匹配 <=，且不剔除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),
    _nups("nups.program.d_date_greater_than", "python", "D_DATE 大于比较文本须复核", "err",
          "在 NUPS 加工程序源文本中搜索 D_DATE 标识符后跟大于号的模式；不判断对象是否为主题表或比较是否属于有效 SQL。",
          "若命中内容实际是全量数据的日期过滤条件，边界可能排除有效记录；检测器无法确认表类型或业务日期约定。",
          "对整个 NUPS 程序源文本执行大小写不敏感正则匹配：D_DATE 标识符边界后允许空白再跟 >；也会匹配 >=，且不剔除注释或字符串。",
          "NUPS Python 加工源文件全文", _NUPS, "rule_dws_py"),

    # FineReport menu and authority rules.
    _fine("fine.menu.root_prefix", "menu", "后台目录路径必须包含数据仓库根路径", "err",
          "检查后台目录路径是否包含规定的数据仓库根路径。",
          "目录路径未包含统一根路径时，导入后的报表可能无法映射到预期目录结构。",
          "读取 menu.txt 每个有效行后，后台路径 cpturl 不包含 required_root_prefix 时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu",
          ("fine_report.menu_normalization.required_root_prefix",)),
    _fine("fine.menu.backend_extension", "menu", "后台目录字段须含小写 .cpt 或 .frm 字样", "err",
          "检查后台目录字段是否同时缺少大小写敏感的 .cpt 与 .frm 子串，不验证其是否为扩展名后缀。",
          "若路径字段未包含受支持模板扩展名字样，发布工具可能无法按预期定位模板；子串命中不证明路径指向有效文件。",
          "当 cpturl 中既不存在大小写敏感的 .cpt，也不存在 .frm 子串时触发；只做子串判断，不验证大小写变体或扩展名位置。",
          "FineReport menu.txt 的后台目录字段", "rule_menu"),
    _fine("fine.menu.backend_department_brackets", "menu", "后台目录部门名称须使用中文括号", "err",
          "检查后台目录是否包含半角括号包围的指定部门名称。",
          "同一部门名称使用不同括号形式会造成目录名称不一致并影响检索。",
          "当 cpturl 包含字面量 (村镇银行发展部) 时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu"),
    _fine("fine.menu.backend_department", "menu", "后台目录部门名须采用登记名称", "err",
          "检查后台目录是否仍使用需要调整的部门名称。",
          "旧部门名称会使报表继续归入已调整的目录分组。",
          "当 cpturl 包含 menu_normalization.replacements 中 locations 含 backend 的任一 source 时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu",
          ("fine_report.menu_normalization.replacements",)),
    _fine("fine.menu.backend_space", "menu", "后台目录路径不得包含空格", "err",
          "检查后台目录字段是否含 ASCII 空格。",
          "空格可能使目录解析、路径匹配或人工检索产生歧义。",
          "当 cpturl 中出现普通空格时触发。",
          "FineReport menu.txt 的后台目录字段", "rule_menu"),
    _fine("fine.menu.frontend_root_prefix", "menu", "前台目录不得包含数据仓库根路径", "err",
          "检查前台目录路径是否含有仅应出现在后台路径中的数据仓库根路径。",
          "前台路径带入后台根路径时，导入目录可能多出一个层级并与预期结构不匹配。",
          "当 finememu 包含 required_root_prefix 时触发；代码检查子串而非仅检查开头。",
          "FineReport menu.txt 的前台目录字段", "rule_menu",
          ("fine_report.menu_normalization.required_root_prefix",)),
    _fine("fine.menu.frontend_department", "menu", "前台目录部门名须采用登记名称", "err",
          "检查前台目录是否仍使用需要调整的部门名称。",
          "旧部门名称会使报表继续归入已调整的目录分组。",
          "当 finememu 包含 menu_normalization.replacements 中 locations 含 menu 的任一 source 时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu",
          ("fine_report.menu_normalization.replacements",)),
    _fine("fine.menu.frontend_finance_department", "menu", "前台目录不得使用旧互联网金融部名称", "err",
          "检查前台目录是否仍使用“互联网金融部”这一旧部门名称。",
          "目录仍使用已调整的部门名称时，报表检索和目录权限可能继续依赖旧分类。",
          "当 menu 替换来源集合含“互联网金融部”且 finememu 也含该字符串时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu",
          ("fine_report.menu_normalization.replacements",)),
    _fine("fine.menu.frontend_department_brackets", "menu", "前台目录部门名称须使用半角括号", "err",
          "检查前台目录是否含全角括号包围的指定部门名称。",
          "括号形式不一致会形成重复或难以匹配的目录名称。",
          "当 finememu 包含字面量（村镇银行发展部）时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu"),
    _fine("fine.menu.frontend_extension", "menu", "前台目录不得包含 CPT 扩展名", "err",
          "检查前台目录字段是否包含大小写敏感的 .cpt 子串。",
          "前台目录字段应标识目录而非模板文件，文件名会造成路径层级混淆。",
          "当 finememu 中出现 .cpt 时触发；该规则不检查 .frm。",
          "FineReport menu.txt 的前台目录字段", "rule_menu"),
    _fine("fine.menu.frontend_space", "menu", "前台目录路径不得包含空格", "err",
          "检查前台目录字段是否含 ASCII 空格。",
          "空格可能使目录解析、路径匹配或人工检索产生歧义。",
          "当 finememu 中出现普通空格时触发。",
          "FineReport menu.txt 的前台目录字段", "rule_menu"),
    _fine("fine.authority.missing_role", "permission", "报表授权角色必须存在于生产", "err",
          "检查 authority.txt 中列出的角色名称是否存在于生产角色元数据。",
          "未登记角色无法按预期授予报表访问权限，可能使用户失去所需访问或权限配置无法生效。",
          "当角色元数据可读取且某一权限项不在 all_role 返回集合中时触发。",
          "FineReport authority.txt 的角色字段", "rule_authority"),
    _fine("fine.authority.missing_menu", "permission", "已授权报表必须存在于报表目录", "err",
          "检查 authority.txt 中规范化后的报表名称是否存在于生产报表或本次 menu 列表。",
          "权限记录引用不存在的目录项时，授权对象无法对应到可访问的报表。",
          "当报表名非空且不在 all_fine 与 menu 名称的合并集合中时触发。",
          "FineReport authority.txt 的报表名称及目录元数据", "rule_authority"),

    # FineReport report/template rules.
    _fine("fine.report.missing_number", "report", "报表模板文件名必须包含编号标记", "err",
          "检查模板文件名是否同时包含左方括号和右方括号。",
          "没有约定编号标记时，报表难以与需求或目录中的编号对应。",
          "当文件名缺少 [ 或 ] 任一字符时触发；不校验括号内编号格式。",
          "FineReport CPT / FRM 模板文件名", "rule_fine"),
    _fine("fine.report.name_space", "report", "报表模板路径不得包含空格", "err",
          "检查传入模板路径是否包含 ASCII 空格。",
          "路径中的空格可能导致文件系统、发布工具或后续路径匹配出现差异。",
          "当 fine_name 任意位置出现普通空格时触发。",
          "FineReport CPT / FRM 模板路径", "rule_fine"),
    _fine("fine.report.distinct_review", "report", "报表模板全文命中 DISTINCT 须核对去重范围", "warn",
          "检查 FineReport 模板原文是否包含 DISTINCT 字符串，不判断去重是否必要，也不限定在提取的 SQL 中。",
          "若 DISTINCT 位于实际查询中，不必要的去重可能增加查询开销；错误去重也可能掩盖关联产生的重复行。",
          "模板原始全文转为大写后包含 DISTINCT 即触发；XML、注释和字符串中的命中也会触发。",
          "FineReport CPT / FRM 模板原始全文", "rule_fine"),
    _fine("fine.report.group_only", "report", "报表模板中的 DIVIDEMODE=\"1\" 片段须复核", "warn",
          "检查模板原始文本是否包含精确 XML 字面量 <ATTR DIVIDEMODE=\"1\"/>；不解析 XML 展示结构。",
          "该单一片段不足以证明模板是否还展示明细行；需结合模板其余配置和预期展示方式人工确认。",
          "当原始模板内容大小写敏感地包含 <ATTR DIVIDEMODE=\"1\"/> 时触发；不判断其是否为唯一展示模式或有效 XML 节点。",
          "FineReport CPT / FRM 模板原始全文", "rule_fine"),
    _fine("fine.report.org_tree_default", "report", "机构树模板须包含预设的用户机构 SQL 模式", "err",
          "检查模板原始文本是否含“权限机构树”标记，并查找预设的登录用户机构 SQL 正则模式。",
          "未匹配该固定 SQL 形态时，规则无法确认模板是否按当前登录用户名限定机构范围，需人工复核实际 SQL 和参数。",
          "当原始模板全文包含“权限机构树”且全文未匹配忽略大小写、允许空白变化的 SELECT MIN(T.NBJGH) FROM DWP.P_SYS_USER_INFO T WHERE T.GH='${FINE_USERNAME}' 正则模式时触发；不绑定特定机构树节点，也只覆盖该文本形态。",
          "FineReport CPT / FRM 模板原始全文", "rule_fine"),
    _fine("fine.report.sensitive_fields", "report", "报表数据集文本命中敏感字段关键词须复核", "warn",
          "在从模板 Query 节点提取的文本中搜索配置的敏感字段关键词，不解析 SQL 字段引用或结果列。",
          "若命中项确为查询字段且未经适当授权展示，可能暴露不必要的个人或账户信息；关键词命中本身不证明字段被选出。",
          "对提取的 Query 文本进行大小写不敏感子串搜索；错误级别关键词当前输出 ERR，其他已配置或默认警告关键词输出 WARN。",
          "FineReport 模板 Query 节点提取文本", "rule_fine",
          ("fine_report.sensitive_field_rules",)),
    _fine("fine.report.hardcoded_date", "report", "报表数据集文本中的日期候选须复核", "warn",
          "在从模板 Query 节点提取的文本中搜索带引号的 YYYYMMDD 或 YYYY-MM-DD 日期候选，并仅保留可解析且年份在 1900–3000 的值。",
          "若候选是实际查询中的固定日期，可能使报表持续查询旧期间或遗漏新期间；正则命中不证明日期具有业务含义。",
          "find_hardcoded_dates 对提取的 Query 文本返回一个或多个候选时触发；扫描文本候选，不判断注释、字符串或日期用途。",
          "FineReport 模板 Query 节点提取文本", "rule_fine"),
    _fine("fine.report.scalar_subquery", "report", "报表数据集文本中的 =(SELECT 模式须复核", "warn",
          "检查提取的 Query 文本是否包含精确子串 =(SELECT，不解析子查询语法。",
          "若该文本属于等号右侧标量子查询且结果多于一行，执行可能失败；本规则不判断语法或查询基数。",
          "提取的 Query 文本转为大写后包含 =(SELECT 即触发；不移除空格、注释或字符串。",
          "FineReport 模板 Query 节点提取文本", "rule_fine"),
    _fine("fine.report.in_subquery", "report", "报表数据集文本中的 IN(SELECT 模式须复核", "warn",
          "检查提取的 Query 文本在移除 JOIN(SELECT 后是否包含 IN(SELECT 子串。",
          "若命中内容属于大型实际子查询，可能扩大扫描范围或增加报表加载时间；文本匹配不证明查询规模或执行计划。",
          "将提取的 Query 文本转为大写并删除 JOIN(SELECT 子串后，包含 IN(SELECT 即触发；不解析 SQL，也不排除注释或字符串。",
          "FineReport 模板 Query 节点提取文本", "rule_fine"),
    _fine("fine.report.end_dt_range", "report", "报表数据集文本中的 .END_DT>= 模式须复核", "err",
          "检查提取的 Query 文本是否包含 .END_DT>= 子串，不确认字段或表类型。",
          "若该模式是拉链表的有效期条件，边界写法可能影响历史版本筛选；命中本身不能证明该业务语义。",
          "提取的 Query 文本转为大写后包含 .END_DT>= 即触发；不解析比较语义，也不排除注释或字符串。",
          "FineReport 模板 Query 节点提取文本", "rule_fine"),
    _fine("fine.report.d_date_to_date", "report", "模板文本中的 D_DATE=TO_DATE(' 字面量须复核", "err",
          "检查模板原始全文是否包含大小写敏感的 D_DATE=TO_DATE(' 子串，不限于提取出的 SQL。",
          "若命中内容位于实际日期过滤表达式中，对日期列套用转换可能影响过滤或分区裁剪；命中本身不确认 SQL 语义。",
          "当原始模板全文大小写敏感地包含 D_DATE=TO_DATE(' 时触发；不解析 XML 或 SQL，也不排除注释和字符串。",
          "FineReport CPT / FRM 模板原始全文", "rule_fine"),
    _fine("fine.report.d_date_literal", "report", "模板文本中的 D_DATE=DATE' 字面量须复核", "err",
          "检查模板原始全文是否包含大小写敏感的 D_DATE=DATE' 子串，不限于提取出的 SQL。",
          "若命中内容位于实际日期过滤表达式中，字面量形式可能不符合项目日期约定；命中本身不确认对象或 SQL 语义。",
          "当原始模板全文大小写敏感地包含 D_DATE=DATE' 时触发；不解析 XML 或 SQL，也不排除注释和字符串。",
          "FineReport CPT / FRM 模板原始全文", "rule_fine"),
    _fine("fine.report.missing_schema", "report", "报表数据集中的未限定名称候选须复核", "warn",
          "检查提取 Query 文本中的 FROM/JOIN/USING 名称及点分隔字符串候选，排除内置名后，判断剩余候选是否含点号。",
          "若命中项确为未限定表引用，默认 schema 可能使不同运行账户解析到不同对象；候选误报需先确认其 SQL 角色。",
          "对提取的 Query 文本由正则提取表名和点分隔字符串；排除内置名称后，候选不含点号即触发。该逻辑不解析 CTE/别名，且注释或字符串可误命中。",
          "FineReport 模板 Query 节点提取文本", "rule_fine"),
)

RULES_BY_ID = MappingProxyType({rule.id: rule for rule in RULES})


def resolve_rule(rule_id: str) -> RuleDefinition | None:
    """Return static metadata for a registered business rule ID."""
    return RULES_BY_ID.get(rule_id)


def rule_inventory() -> tuple[dict[str, object], ...]:
    """Return a machine-readable inventory using the short ``severity`` key."""
    inventory = []
    for rule in RULES:
        entry = asdict(rule)
        entry["severity"] = entry.pop("default_severity")
        inventory.append(entry)
    return tuple(inventory)
