default_profile: sqlite

profiles:
  sqlite:
    type: sqlite
    path: backend/data/app.db

  local_pg:
    type: postgresql
    host: 127.0.0.1
    port: 5432
    database: code_audit
    username: change_me
    password: change_me
    schema: public

  local_dws:
    type: dws
    host: 127.0.0.1
    port: 8000
    database: code_audit
    username: change_me
    password: change_me
    schema: public
